package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcBairro generated by hbm2java
 */
public class JrcBairro  implements java.io.Serializable {


     private long idBairro;
     private JrcEmpresa jrcEmpresa;
     private JrcLocalidade jrcLocalidade;
     private JrcUsuario jrcUsuario;
     private String descBreve;
     private String descLonga;
     private Integer chaveDne;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private Set jrcNotaFiscalsForEmIdBairro = new HashSet(0);
     private Set jrcNotaFiscalsForDrIdBairro = new HashSet(0);
     private Set jrcNotaFiscalsForTrIdBairro = new HashSet(0);
     private Set jrcLogradouros = new HashSet(0);
     private Set jrcPedidoVendas = new HashSet(0);

    public JrcBairro() {
    }

	
    public JrcBairro(long idBairro, JrcEmpresa jrcEmpresa, JrcLocalidade jrcLocalidade, JrcUsuario jrcUsuario, String descLonga, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idBairro = idBairro;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcLocalidade = jrcLocalidade;
        this.jrcUsuario = jrcUsuario;
        this.descLonga = descLonga;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcBairro(long idBairro, JrcEmpresa jrcEmpresa, JrcLocalidade jrcLocalidade, JrcUsuario jrcUsuario, String descBreve, String descLonga, Integer chaveDne, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, Set jrcNotaFiscalsForEmIdBairro, Set jrcNotaFiscalsForDrIdBairro, Set jrcNotaFiscalsForTrIdBairro, Set jrcLogradouros, Set jrcPedidoVendas) {
       this.idBairro = idBairro;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcLocalidade = jrcLocalidade;
       this.jrcUsuario = jrcUsuario;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.chaveDne = chaveDne;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.jrcNotaFiscalsForEmIdBairro = jrcNotaFiscalsForEmIdBairro;
       this.jrcNotaFiscalsForDrIdBairro = jrcNotaFiscalsForDrIdBairro;
       this.jrcNotaFiscalsForTrIdBairro = jrcNotaFiscalsForTrIdBairro;
       this.jrcLogradouros = jrcLogradouros;
       this.jrcPedidoVendas = jrcPedidoVendas;
    }
   
    public long getIdBairro() {
        return this.idBairro;
    }
    
    public void setIdBairro(long idBairro) {
        this.idBairro = idBairro;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcLocalidade getJrcLocalidade() {
        return this.jrcLocalidade;
    }
    
    public void setJrcLocalidade(JrcLocalidade jrcLocalidade) {
        this.jrcLocalidade = jrcLocalidade;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public Integer getChaveDne() {
        return this.chaveDne;
    }
    
    public void setChaveDne(Integer chaveDne) {
        this.chaveDne = chaveDne;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public Set getJrcNotaFiscalsForEmIdBairro() {
        return this.jrcNotaFiscalsForEmIdBairro;
    }
    
    public void setJrcNotaFiscalsForEmIdBairro(Set jrcNotaFiscalsForEmIdBairro) {
        this.jrcNotaFiscalsForEmIdBairro = jrcNotaFiscalsForEmIdBairro;
    }
    public Set getJrcNotaFiscalsForDrIdBairro() {
        return this.jrcNotaFiscalsForDrIdBairro;
    }
    
    public void setJrcNotaFiscalsForDrIdBairro(Set jrcNotaFiscalsForDrIdBairro) {
        this.jrcNotaFiscalsForDrIdBairro = jrcNotaFiscalsForDrIdBairro;
    }
    public Set getJrcNotaFiscalsForTrIdBairro() {
        return this.jrcNotaFiscalsForTrIdBairro;
    }
    
    public void setJrcNotaFiscalsForTrIdBairro(Set jrcNotaFiscalsForTrIdBairro) {
        this.jrcNotaFiscalsForTrIdBairro = jrcNotaFiscalsForTrIdBairro;
    }
    public Set getJrcLogradouros() {
        return this.jrcLogradouros;
    }
    
    public void setJrcLogradouros(Set jrcLogradouros) {
        this.jrcLogradouros = jrcLogradouros;
    }
    public Set getJrcPedidoVendas() {
        return this.jrcPedidoVendas;
    }
    
    public void setJrcPedidoVendas(Set jrcPedidoVendas) {
        this.jrcPedidoVendas = jrcPedidoVendas;
    }




}


