package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcCarneConfig generated by hbm2java
 */
public class JrcCarneConfig  implements java.io.Serializable {


     private long idCarneConfig;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String codBanco;
     private String banco;
     private String localPagto;
     private String cedenteNome;
     private Long cedenteAgencia;
     private String cedenteAgenciaDigito;
     private Long cedenteConta;
     private String cedenteContaDigito;
     private String especieDocto;
     private String aceite;
     private String usoBanco;
     private String cip;
     private String carteira;
     private String especieMoeda;
     private String instrucao01;
     private String instrucao02;
     private String instrucao03;
     private String instrucao04;
     private String instrucao05;
     private String instrucao06;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private Long cedenteCpfCnpj;
     private String bancoDigito;
     private Byte cedenteSubconta;
     private String cedenteEndereco;
     private String cedenteBairro;
     private String cedenteCidade;
     private String cedenteUf;
     private Integer cedenteCep;
     private String codEspecieDocto;
     private String variacaoCarteira;
     private String foneSac;
     private String foneSacEsp;
     private String foneOuvidoria;
     private String flagLayoutBoleto;
     private Set jrcTipoVendas = new HashSet(0);

    public JrcCarneConfig() {
    }

	
    public JrcCarneConfig(long idCarneConfig, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idCarneConfig = idCarneConfig;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcCarneConfig(long idCarneConfig, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String codBanco, String banco, String localPagto, String cedenteNome, Long cedenteAgencia, String cedenteAgenciaDigito, Long cedenteConta, String cedenteContaDigito, String especieDocto, String aceite, String usoBanco, String cip, String carteira, String especieMoeda, String instrucao01, String instrucao02, String instrucao03, String instrucao04, String instrucao05, String instrucao06, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, Long cedenteCpfCnpj, String bancoDigito, Byte cedenteSubconta, String cedenteEndereco, String cedenteBairro, String cedenteCidade, String cedenteUf, Integer cedenteCep, String codEspecieDocto, String variacaoCarteira, String foneSac, String foneSacEsp, String foneOuvidoria, String flagLayoutBoleto, Set jrcTipoVendas) {
       this.idCarneConfig = idCarneConfig;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.codBanco = codBanco;
       this.banco = banco;
       this.localPagto = localPagto;
       this.cedenteNome = cedenteNome;
       this.cedenteAgencia = cedenteAgencia;
       this.cedenteAgenciaDigito = cedenteAgenciaDigito;
       this.cedenteConta = cedenteConta;
       this.cedenteContaDigito = cedenteContaDigito;
       this.especieDocto = especieDocto;
       this.aceite = aceite;
       this.usoBanco = usoBanco;
       this.cip = cip;
       this.carteira = carteira;
       this.especieMoeda = especieMoeda;
       this.instrucao01 = instrucao01;
       this.instrucao02 = instrucao02;
       this.instrucao03 = instrucao03;
       this.instrucao04 = instrucao04;
       this.instrucao05 = instrucao05;
       this.instrucao06 = instrucao06;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.cedenteCpfCnpj = cedenteCpfCnpj;
       this.bancoDigito = bancoDigito;
       this.cedenteSubconta = cedenteSubconta;
       this.cedenteEndereco = cedenteEndereco;
       this.cedenteBairro = cedenteBairro;
       this.cedenteCidade = cedenteCidade;
       this.cedenteUf = cedenteUf;
       this.cedenteCep = cedenteCep;
       this.codEspecieDocto = codEspecieDocto;
       this.variacaoCarteira = variacaoCarteira;
       this.foneSac = foneSac;
       this.foneSacEsp = foneSacEsp;
       this.foneOuvidoria = foneOuvidoria;
       this.flagLayoutBoleto = flagLayoutBoleto;
       this.jrcTipoVendas = jrcTipoVendas;
    }
   
    public long getIdCarneConfig() {
        return this.idCarneConfig;
    }
    
    public void setIdCarneConfig(long idCarneConfig) {
        this.idCarneConfig = idCarneConfig;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getCodBanco() {
        return this.codBanco;
    }
    
    public void setCodBanco(String codBanco) {
        this.codBanco = codBanco;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getLocalPagto() {
        return this.localPagto;
    }
    
    public void setLocalPagto(String localPagto) {
        this.localPagto = localPagto;
    }
    public String getCedenteNome() {
        return this.cedenteNome;
    }
    
    public void setCedenteNome(String cedenteNome) {
        this.cedenteNome = cedenteNome;
    }
    public Long getCedenteAgencia() {
        return this.cedenteAgencia;
    }
    
    public void setCedenteAgencia(Long cedenteAgencia) {
        this.cedenteAgencia = cedenteAgencia;
    }
    public String getCedenteAgenciaDigito() {
        return this.cedenteAgenciaDigito;
    }
    
    public void setCedenteAgenciaDigito(String cedenteAgenciaDigito) {
        this.cedenteAgenciaDigito = cedenteAgenciaDigito;
    }
    public Long getCedenteConta() {
        return this.cedenteConta;
    }
    
    public void setCedenteConta(Long cedenteConta) {
        this.cedenteConta = cedenteConta;
    }
    public String getCedenteContaDigito() {
        return this.cedenteContaDigito;
    }
    
    public void setCedenteContaDigito(String cedenteContaDigito) {
        this.cedenteContaDigito = cedenteContaDigito;
    }
    public String getEspecieDocto() {
        return this.especieDocto;
    }
    
    public void setEspecieDocto(String especieDocto) {
        this.especieDocto = especieDocto;
    }
    public String getAceite() {
        return this.aceite;
    }
    
    public void setAceite(String aceite) {
        this.aceite = aceite;
    }
    public String getUsoBanco() {
        return this.usoBanco;
    }
    
    public void setUsoBanco(String usoBanco) {
        this.usoBanco = usoBanco;
    }
    public String getCip() {
        return this.cip;
    }
    
    public void setCip(String cip) {
        this.cip = cip;
    }
    public String getCarteira() {
        return this.carteira;
    }
    
    public void setCarteira(String carteira) {
        this.carteira = carteira;
    }
    public String getEspecieMoeda() {
        return this.especieMoeda;
    }
    
    public void setEspecieMoeda(String especieMoeda) {
        this.especieMoeda = especieMoeda;
    }
    public String getInstrucao01() {
        return this.instrucao01;
    }
    
    public void setInstrucao01(String instrucao01) {
        this.instrucao01 = instrucao01;
    }
    public String getInstrucao02() {
        return this.instrucao02;
    }
    
    public void setInstrucao02(String instrucao02) {
        this.instrucao02 = instrucao02;
    }
    public String getInstrucao03() {
        return this.instrucao03;
    }
    
    public void setInstrucao03(String instrucao03) {
        this.instrucao03 = instrucao03;
    }
    public String getInstrucao04() {
        return this.instrucao04;
    }
    
    public void setInstrucao04(String instrucao04) {
        this.instrucao04 = instrucao04;
    }
    public String getInstrucao05() {
        return this.instrucao05;
    }
    
    public void setInstrucao05(String instrucao05) {
        this.instrucao05 = instrucao05;
    }
    public String getInstrucao06() {
        return this.instrucao06;
    }
    
    public void setInstrucao06(String instrucao06) {
        this.instrucao06 = instrucao06;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public Long getCedenteCpfCnpj() {
        return this.cedenteCpfCnpj;
    }
    
    public void setCedenteCpfCnpj(Long cedenteCpfCnpj) {
        this.cedenteCpfCnpj = cedenteCpfCnpj;
    }
    public String getBancoDigito() {
        return this.bancoDigito;
    }
    
    public void setBancoDigito(String bancoDigito) {
        this.bancoDigito = bancoDigito;
    }
    public Byte getCedenteSubconta() {
        return this.cedenteSubconta;
    }
    
    public void setCedenteSubconta(Byte cedenteSubconta) {
        this.cedenteSubconta = cedenteSubconta;
    }
    public String getCedenteEndereco() {
        return this.cedenteEndereco;
    }
    
    public void setCedenteEndereco(String cedenteEndereco) {
        this.cedenteEndereco = cedenteEndereco;
    }
    public String getCedenteBairro() {
        return this.cedenteBairro;
    }
    
    public void setCedenteBairro(String cedenteBairro) {
        this.cedenteBairro = cedenteBairro;
    }
    public String getCedenteCidade() {
        return this.cedenteCidade;
    }
    
    public void setCedenteCidade(String cedenteCidade) {
        this.cedenteCidade = cedenteCidade;
    }
    public String getCedenteUf() {
        return this.cedenteUf;
    }
    
    public void setCedenteUf(String cedenteUf) {
        this.cedenteUf = cedenteUf;
    }
    public Integer getCedenteCep() {
        return this.cedenteCep;
    }
    
    public void setCedenteCep(Integer cedenteCep) {
        this.cedenteCep = cedenteCep;
    }
    public String getCodEspecieDocto() {
        return this.codEspecieDocto;
    }
    
    public void setCodEspecieDocto(String codEspecieDocto) {
        this.codEspecieDocto = codEspecieDocto;
    }
    public String getVariacaoCarteira() {
        return this.variacaoCarteira;
    }
    
    public void setVariacaoCarteira(String variacaoCarteira) {
        this.variacaoCarteira = variacaoCarteira;
    }
    public String getFoneSac() {
        return this.foneSac;
    }
    
    public void setFoneSac(String foneSac) {
        this.foneSac = foneSac;
    }
    public String getFoneSacEsp() {
        return this.foneSacEsp;
    }
    
    public void setFoneSacEsp(String foneSacEsp) {
        this.foneSacEsp = foneSacEsp;
    }
    public String getFoneOuvidoria() {
        return this.foneOuvidoria;
    }
    
    public void setFoneOuvidoria(String foneOuvidoria) {
        this.foneOuvidoria = foneOuvidoria;
    }
    public String getFlagLayoutBoleto() {
        return this.flagLayoutBoleto;
    }
    
    public void setFlagLayoutBoleto(String flagLayoutBoleto) {
        this.flagLayoutBoleto = flagLayoutBoleto;
    }
    public Set getJrcTipoVendas() {
        return this.jrcTipoVendas;
    }
    
    public void setJrcTipoVendas(Set jrcTipoVendas) {
        this.jrcTipoVendas = jrcTipoVendas;
    }




}


