package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcFinBordero generated by hbm2java
 */
public class JrcFinBordero  implements java.io.Serializable {


     private long idFinBordero;
     private JrcFinLancamento jrcFinLancamentoByIdFinLanctoBanco;
     private JrcFinLancamento jrcFinLancamentoByIdFinLanctoBancoDev;
     private JrcEmpresa jrcEmpresa;
     private JrcPessoa jrcPessoa;
     private JrcUsuario jrcUsuario;
     private String flagTipoBordero;
     private String descricao;
     private BigDecimal vrLancto;
     private BigDecimal vrBordero;
     private String flagStatus;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String observacao;
     private Set jrcFinLancamentos = new HashSet(0);

    public JrcFinBordero() {
    }

	
    public JrcFinBordero(long idFinBordero, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String flagTipoBordero, String descricao, BigDecimal vrLancto, BigDecimal vrBordero, String flagStatus, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idFinBordero = idFinBordero;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.flagTipoBordero = flagTipoBordero;
        this.descricao = descricao;
        this.vrLancto = vrLancto;
        this.vrBordero = vrBordero;
        this.flagStatus = flagStatus;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcFinBordero(long idFinBordero, JrcFinLancamento jrcFinLancamentoByIdFinLanctoBanco, JrcFinLancamento jrcFinLancamentoByIdFinLanctoBancoDev, JrcEmpresa jrcEmpresa, JrcPessoa jrcPessoa, JrcUsuario jrcUsuario, String flagTipoBordero, String descricao, BigDecimal vrLancto, BigDecimal vrBordero, String flagStatus, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String observacao, Set jrcFinLancamentos) {
       this.idFinBordero = idFinBordero;
       this.jrcFinLancamentoByIdFinLanctoBanco = jrcFinLancamentoByIdFinLanctoBanco;
       this.jrcFinLancamentoByIdFinLanctoBancoDev = jrcFinLancamentoByIdFinLanctoBancoDev;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcPessoa = jrcPessoa;
       this.jrcUsuario = jrcUsuario;
       this.flagTipoBordero = flagTipoBordero;
       this.descricao = descricao;
       this.vrLancto = vrLancto;
       this.vrBordero = vrBordero;
       this.flagStatus = flagStatus;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.observacao = observacao;
       this.jrcFinLancamentos = jrcFinLancamentos;
    }
   
    public long getIdFinBordero() {
        return this.idFinBordero;
    }
    
    public void setIdFinBordero(long idFinBordero) {
        this.idFinBordero = idFinBordero;
    }
    public JrcFinLancamento getJrcFinLancamentoByIdFinLanctoBanco() {
        return this.jrcFinLancamentoByIdFinLanctoBanco;
    }
    
    public void setJrcFinLancamentoByIdFinLanctoBanco(JrcFinLancamento jrcFinLancamentoByIdFinLanctoBanco) {
        this.jrcFinLancamentoByIdFinLanctoBanco = jrcFinLancamentoByIdFinLanctoBanco;
    }
    public JrcFinLancamento getJrcFinLancamentoByIdFinLanctoBancoDev() {
        return this.jrcFinLancamentoByIdFinLanctoBancoDev;
    }
    
    public void setJrcFinLancamentoByIdFinLanctoBancoDev(JrcFinLancamento jrcFinLancamentoByIdFinLanctoBancoDev) {
        this.jrcFinLancamentoByIdFinLanctoBancoDev = jrcFinLancamentoByIdFinLanctoBancoDev;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcPessoa getJrcPessoa() {
        return this.jrcPessoa;
    }
    
    public void setJrcPessoa(JrcPessoa jrcPessoa) {
        this.jrcPessoa = jrcPessoa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getFlagTipoBordero() {
        return this.flagTipoBordero;
    }
    
    public void setFlagTipoBordero(String flagTipoBordero) {
        this.flagTipoBordero = flagTipoBordero;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getVrLancto() {
        return this.vrLancto;
    }
    
    public void setVrLancto(BigDecimal vrLancto) {
        this.vrLancto = vrLancto;
    }
    public BigDecimal getVrBordero() {
        return this.vrBordero;
    }
    
    public void setVrBordero(BigDecimal vrBordero) {
        this.vrBordero = vrBordero;
    }
    public String getFlagStatus() {
        return this.flagStatus;
    }
    
    public void setFlagStatus(String flagStatus) {
        this.flagStatus = flagStatus;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Set getJrcFinLancamentos() {
        return this.jrcFinLancamentos;
    }
    
    public void setJrcFinLancamentos(Set jrcFinLancamentos) {
        this.jrcFinLancamentos = jrcFinLancamentos;
    }




}


