package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcHorarioSemanal generated by hbm2java
 */
public class JrcHorarioSemanal  implements java.io.Serializable {


     private long idHorarioSemanal;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String descBreve;
     private String descLonga;
     private Byte EHhT1Seg;
     private Byte EMiT1Seg;
     private Byte SHhT1Seg;
     private Byte SMiT1Seg;
     private Byte EHhT2Seg;
     private Byte EMiT2Seg;
     private Byte SHhT2Seg;
     private Byte SMiT2Seg;
     private Byte EHhT1Ter;
     private Byte EMiT1Ter;
     private Byte SHhT1Ter;
     private Byte SMiT1Ter;
     private Byte EHhT2Ter;
     private Byte EMiT2Ter;
     private Byte SHhT2Ter;
     private Byte SMiT2Ter;
     private Byte EHhT1Qua;
     private Byte EMiT1Qua;
     private Byte SHhT1Qua;
     private Byte SMiT1Qua;
     private Byte EHhT2Qua;
     private Byte EMiT2Qua;
     private Byte SHhT2Qua;
     private Byte SMiT2Qua;
     private Byte EHhT1Qui;
     private Byte EMiT1Qui;
     private Byte SHhT1Qui;
     private Byte SMiT1Qui;
     private Byte EHhT2Qui;
     private Byte EMiT2Qui;
     private Byte SHhT2Qui;
     private Byte SMiT2Qui;
     private Byte EHhT1Sex;
     private Byte EMiT1Sex;
     private Byte SHhT1Sex;
     private Byte SMiT1Sex;
     private Byte EHhT2Sex;
     private Byte EMiT2Sex;
     private Byte SHhT2Sex;
     private Byte SMiT2Sex;
     private Byte EHhT1Sab;
     private Byte EMiT1Sab;
     private Byte SHhT1Sab;
     private Byte SMiT1Sab;
     private Byte EHhT2Sab;
     private Byte EMiT2Sab;
     private Byte SHhT2Sab;
     private Byte SMiT2Sab;
     private Byte EHhT1Dom;
     private Byte EMiT1Dom;
     private Byte SHhT1Dom;
     private Byte SMiT1Dom;
     private Byte EHhT2Dom;
     private Byte EMiT2Dom;
     private Byte SHhT2Dom;
     private Byte SMiT2Dom;
     private Boolean indPermiteFeriado;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private Short miToleranciaExpediente;
     private Set jrcUsuarios = new HashSet(0);

    public JrcHorarioSemanal() {
    }

	
    public JrcHorarioSemanal(long idHorarioSemanal, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String descBreve, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idHorarioSemanal = idHorarioSemanal;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.descBreve = descBreve;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcHorarioSemanal(long idHorarioSemanal, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String descBreve, String descLonga, Byte EHhT1Seg, Byte EMiT1Seg, Byte SHhT1Seg, Byte SMiT1Seg, Byte EHhT2Seg, Byte EMiT2Seg, Byte SHhT2Seg, Byte SMiT2Seg, Byte EHhT1Ter, Byte EMiT1Ter, Byte SHhT1Ter, Byte SMiT1Ter, Byte EHhT2Ter, Byte EMiT2Ter, Byte SHhT2Ter, Byte SMiT2Ter, Byte EHhT1Qua, Byte EMiT1Qua, Byte SHhT1Qua, Byte SMiT1Qua, Byte EHhT2Qua, Byte EMiT2Qua, Byte SHhT2Qua, Byte SMiT2Qua, Byte EHhT1Qui, Byte EMiT1Qui, Byte SHhT1Qui, Byte SMiT1Qui, Byte EHhT2Qui, Byte EMiT2Qui, Byte SHhT2Qui, Byte SMiT2Qui, Byte EHhT1Sex, Byte EMiT1Sex, Byte SHhT1Sex, Byte SMiT1Sex, Byte EHhT2Sex, Byte EMiT2Sex, Byte SHhT2Sex, Byte SMiT2Sex, Byte EHhT1Sab, Byte EMiT1Sab, Byte SHhT1Sab, Byte SMiT1Sab, Byte EHhT2Sab, Byte EMiT2Sab, Byte SHhT2Sab, Byte SMiT2Sab, Byte EHhT1Dom, Byte EMiT1Dom, Byte SHhT1Dom, Byte SMiT1Dom, Byte EHhT2Dom, Byte EMiT2Dom, Byte SHhT2Dom, Byte SMiT2Dom, Boolean indPermiteFeriado, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, Short miToleranciaExpediente, Set jrcUsuarios) {
       this.idHorarioSemanal = idHorarioSemanal;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.EHhT1Seg = EHhT1Seg;
       this.EMiT1Seg = EMiT1Seg;
       this.SHhT1Seg = SHhT1Seg;
       this.SMiT1Seg = SMiT1Seg;
       this.EHhT2Seg = EHhT2Seg;
       this.EMiT2Seg = EMiT2Seg;
       this.SHhT2Seg = SHhT2Seg;
       this.SMiT2Seg = SMiT2Seg;
       this.EHhT1Ter = EHhT1Ter;
       this.EMiT1Ter = EMiT1Ter;
       this.SHhT1Ter = SHhT1Ter;
       this.SMiT1Ter = SMiT1Ter;
       this.EHhT2Ter = EHhT2Ter;
       this.EMiT2Ter = EMiT2Ter;
       this.SHhT2Ter = SHhT2Ter;
       this.SMiT2Ter = SMiT2Ter;
       this.EHhT1Qua = EHhT1Qua;
       this.EMiT1Qua = EMiT1Qua;
       this.SHhT1Qua = SHhT1Qua;
       this.SMiT1Qua = SMiT1Qua;
       this.EHhT2Qua = EHhT2Qua;
       this.EMiT2Qua = EMiT2Qua;
       this.SHhT2Qua = SHhT2Qua;
       this.SMiT2Qua = SMiT2Qua;
       this.EHhT1Qui = EHhT1Qui;
       this.EMiT1Qui = EMiT1Qui;
       this.SHhT1Qui = SHhT1Qui;
       this.SMiT1Qui = SMiT1Qui;
       this.EHhT2Qui = EHhT2Qui;
       this.EMiT2Qui = EMiT2Qui;
       this.SHhT2Qui = SHhT2Qui;
       this.SMiT2Qui = SMiT2Qui;
       this.EHhT1Sex = EHhT1Sex;
       this.EMiT1Sex = EMiT1Sex;
       this.SHhT1Sex = SHhT1Sex;
       this.SMiT1Sex = SMiT1Sex;
       this.EHhT2Sex = EHhT2Sex;
       this.EMiT2Sex = EMiT2Sex;
       this.SHhT2Sex = SHhT2Sex;
       this.SMiT2Sex = SMiT2Sex;
       this.EHhT1Sab = EHhT1Sab;
       this.EMiT1Sab = EMiT1Sab;
       this.SHhT1Sab = SHhT1Sab;
       this.SMiT1Sab = SMiT1Sab;
       this.EHhT2Sab = EHhT2Sab;
       this.EMiT2Sab = EMiT2Sab;
       this.SHhT2Sab = SHhT2Sab;
       this.SMiT2Sab = SMiT2Sab;
       this.EHhT1Dom = EHhT1Dom;
       this.EMiT1Dom = EMiT1Dom;
       this.SHhT1Dom = SHhT1Dom;
       this.SMiT1Dom = SMiT1Dom;
       this.EHhT2Dom = EHhT2Dom;
       this.EMiT2Dom = EMiT2Dom;
       this.SHhT2Dom = SHhT2Dom;
       this.SMiT2Dom = SMiT2Dom;
       this.indPermiteFeriado = indPermiteFeriado;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.miToleranciaExpediente = miToleranciaExpediente;
       this.jrcUsuarios = jrcUsuarios;
    }
   
    public long getIdHorarioSemanal() {
        return this.idHorarioSemanal;
    }
    
    public void setIdHorarioSemanal(long idHorarioSemanal) {
        this.idHorarioSemanal = idHorarioSemanal;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public Byte getEHhT1Seg() {
        return this.EHhT1Seg;
    }
    
    public void setEHhT1Seg(Byte EHhT1Seg) {
        this.EHhT1Seg = EHhT1Seg;
    }
    public Byte getEMiT1Seg() {
        return this.EMiT1Seg;
    }
    
    public void setEMiT1Seg(Byte EMiT1Seg) {
        this.EMiT1Seg = EMiT1Seg;
    }
    public Byte getSHhT1Seg() {
        return this.SHhT1Seg;
    }
    
    public void setSHhT1Seg(Byte SHhT1Seg) {
        this.SHhT1Seg = SHhT1Seg;
    }
    public Byte getSMiT1Seg() {
        return this.SMiT1Seg;
    }
    
    public void setSMiT1Seg(Byte SMiT1Seg) {
        this.SMiT1Seg = SMiT1Seg;
    }
    public Byte getEHhT2Seg() {
        return this.EHhT2Seg;
    }
    
    public void setEHhT2Seg(Byte EHhT2Seg) {
        this.EHhT2Seg = EHhT2Seg;
    }
    public Byte getEMiT2Seg() {
        return this.EMiT2Seg;
    }
    
    public void setEMiT2Seg(Byte EMiT2Seg) {
        this.EMiT2Seg = EMiT2Seg;
    }
    public Byte getSHhT2Seg() {
        return this.SHhT2Seg;
    }
    
    public void setSHhT2Seg(Byte SHhT2Seg) {
        this.SHhT2Seg = SHhT2Seg;
    }
    public Byte getSMiT2Seg() {
        return this.SMiT2Seg;
    }
    
    public void setSMiT2Seg(Byte SMiT2Seg) {
        this.SMiT2Seg = SMiT2Seg;
    }
    public Byte getEHhT1Ter() {
        return this.EHhT1Ter;
    }
    
    public void setEHhT1Ter(Byte EHhT1Ter) {
        this.EHhT1Ter = EHhT1Ter;
    }
    public Byte getEMiT1Ter() {
        return this.EMiT1Ter;
    }
    
    public void setEMiT1Ter(Byte EMiT1Ter) {
        this.EMiT1Ter = EMiT1Ter;
    }
    public Byte getSHhT1Ter() {
        return this.SHhT1Ter;
    }
    
    public void setSHhT1Ter(Byte SHhT1Ter) {
        this.SHhT1Ter = SHhT1Ter;
    }
    public Byte getSMiT1Ter() {
        return this.SMiT1Ter;
    }
    
    public void setSMiT1Ter(Byte SMiT1Ter) {
        this.SMiT1Ter = SMiT1Ter;
    }
    public Byte getEHhT2Ter() {
        return this.EHhT2Ter;
    }
    
    public void setEHhT2Ter(Byte EHhT2Ter) {
        this.EHhT2Ter = EHhT2Ter;
    }
    public Byte getEMiT2Ter() {
        return this.EMiT2Ter;
    }
    
    public void setEMiT2Ter(Byte EMiT2Ter) {
        this.EMiT2Ter = EMiT2Ter;
    }
    public Byte getSHhT2Ter() {
        return this.SHhT2Ter;
    }
    
    public void setSHhT2Ter(Byte SHhT2Ter) {
        this.SHhT2Ter = SHhT2Ter;
    }
    public Byte getSMiT2Ter() {
        return this.SMiT2Ter;
    }
    
    public void setSMiT2Ter(Byte SMiT2Ter) {
        this.SMiT2Ter = SMiT2Ter;
    }
    public Byte getEHhT1Qua() {
        return this.EHhT1Qua;
    }
    
    public void setEHhT1Qua(Byte EHhT1Qua) {
        this.EHhT1Qua = EHhT1Qua;
    }
    public Byte getEMiT1Qua() {
        return this.EMiT1Qua;
    }
    
    public void setEMiT1Qua(Byte EMiT1Qua) {
        this.EMiT1Qua = EMiT1Qua;
    }
    public Byte getSHhT1Qua() {
        return this.SHhT1Qua;
    }
    
    public void setSHhT1Qua(Byte SHhT1Qua) {
        this.SHhT1Qua = SHhT1Qua;
    }
    public Byte getSMiT1Qua() {
        return this.SMiT1Qua;
    }
    
    public void setSMiT1Qua(Byte SMiT1Qua) {
        this.SMiT1Qua = SMiT1Qua;
    }
    public Byte getEHhT2Qua() {
        return this.EHhT2Qua;
    }
    
    public void setEHhT2Qua(Byte EHhT2Qua) {
        this.EHhT2Qua = EHhT2Qua;
    }
    public Byte getEMiT2Qua() {
        return this.EMiT2Qua;
    }
    
    public void setEMiT2Qua(Byte EMiT2Qua) {
        this.EMiT2Qua = EMiT2Qua;
    }
    public Byte getSHhT2Qua() {
        return this.SHhT2Qua;
    }
    
    public void setSHhT2Qua(Byte SHhT2Qua) {
        this.SHhT2Qua = SHhT2Qua;
    }
    public Byte getSMiT2Qua() {
        return this.SMiT2Qua;
    }
    
    public void setSMiT2Qua(Byte SMiT2Qua) {
        this.SMiT2Qua = SMiT2Qua;
    }
    public Byte getEHhT1Qui() {
        return this.EHhT1Qui;
    }
    
    public void setEHhT1Qui(Byte EHhT1Qui) {
        this.EHhT1Qui = EHhT1Qui;
    }
    public Byte getEMiT1Qui() {
        return this.EMiT1Qui;
    }
    
    public void setEMiT1Qui(Byte EMiT1Qui) {
        this.EMiT1Qui = EMiT1Qui;
    }
    public Byte getSHhT1Qui() {
        return this.SHhT1Qui;
    }
    
    public void setSHhT1Qui(Byte SHhT1Qui) {
        this.SHhT1Qui = SHhT1Qui;
    }
    public Byte getSMiT1Qui() {
        return this.SMiT1Qui;
    }
    
    public void setSMiT1Qui(Byte SMiT1Qui) {
        this.SMiT1Qui = SMiT1Qui;
    }
    public Byte getEHhT2Qui() {
        return this.EHhT2Qui;
    }
    
    public void setEHhT2Qui(Byte EHhT2Qui) {
        this.EHhT2Qui = EHhT2Qui;
    }
    public Byte getEMiT2Qui() {
        return this.EMiT2Qui;
    }
    
    public void setEMiT2Qui(Byte EMiT2Qui) {
        this.EMiT2Qui = EMiT2Qui;
    }
    public Byte getSHhT2Qui() {
        return this.SHhT2Qui;
    }
    
    public void setSHhT2Qui(Byte SHhT2Qui) {
        this.SHhT2Qui = SHhT2Qui;
    }
    public Byte getSMiT2Qui() {
        return this.SMiT2Qui;
    }
    
    public void setSMiT2Qui(Byte SMiT2Qui) {
        this.SMiT2Qui = SMiT2Qui;
    }
    public Byte getEHhT1Sex() {
        return this.EHhT1Sex;
    }
    
    public void setEHhT1Sex(Byte EHhT1Sex) {
        this.EHhT1Sex = EHhT1Sex;
    }
    public Byte getEMiT1Sex() {
        return this.EMiT1Sex;
    }
    
    public void setEMiT1Sex(Byte EMiT1Sex) {
        this.EMiT1Sex = EMiT1Sex;
    }
    public Byte getSHhT1Sex() {
        return this.SHhT1Sex;
    }
    
    public void setSHhT1Sex(Byte SHhT1Sex) {
        this.SHhT1Sex = SHhT1Sex;
    }
    public Byte getSMiT1Sex() {
        return this.SMiT1Sex;
    }
    
    public void setSMiT1Sex(Byte SMiT1Sex) {
        this.SMiT1Sex = SMiT1Sex;
    }
    public Byte getEHhT2Sex() {
        return this.EHhT2Sex;
    }
    
    public void setEHhT2Sex(Byte EHhT2Sex) {
        this.EHhT2Sex = EHhT2Sex;
    }
    public Byte getEMiT2Sex() {
        return this.EMiT2Sex;
    }
    
    public void setEMiT2Sex(Byte EMiT2Sex) {
        this.EMiT2Sex = EMiT2Sex;
    }
    public Byte getSHhT2Sex() {
        return this.SHhT2Sex;
    }
    
    public void setSHhT2Sex(Byte SHhT2Sex) {
        this.SHhT2Sex = SHhT2Sex;
    }
    public Byte getSMiT2Sex() {
        return this.SMiT2Sex;
    }
    
    public void setSMiT2Sex(Byte SMiT2Sex) {
        this.SMiT2Sex = SMiT2Sex;
    }
    public Byte getEHhT1Sab() {
        return this.EHhT1Sab;
    }
    
    public void setEHhT1Sab(Byte EHhT1Sab) {
        this.EHhT1Sab = EHhT1Sab;
    }
    public Byte getEMiT1Sab() {
        return this.EMiT1Sab;
    }
    
    public void setEMiT1Sab(Byte EMiT1Sab) {
        this.EMiT1Sab = EMiT1Sab;
    }
    public Byte getSHhT1Sab() {
        return this.SHhT1Sab;
    }
    
    public void setSHhT1Sab(Byte SHhT1Sab) {
        this.SHhT1Sab = SHhT1Sab;
    }
    public Byte getSMiT1Sab() {
        return this.SMiT1Sab;
    }
    
    public void setSMiT1Sab(Byte SMiT1Sab) {
        this.SMiT1Sab = SMiT1Sab;
    }
    public Byte getEHhT2Sab() {
        return this.EHhT2Sab;
    }
    
    public void setEHhT2Sab(Byte EHhT2Sab) {
        this.EHhT2Sab = EHhT2Sab;
    }
    public Byte getEMiT2Sab() {
        return this.EMiT2Sab;
    }
    
    public void setEMiT2Sab(Byte EMiT2Sab) {
        this.EMiT2Sab = EMiT2Sab;
    }
    public Byte getSHhT2Sab() {
        return this.SHhT2Sab;
    }
    
    public void setSHhT2Sab(Byte SHhT2Sab) {
        this.SHhT2Sab = SHhT2Sab;
    }
    public Byte getSMiT2Sab() {
        return this.SMiT2Sab;
    }
    
    public void setSMiT2Sab(Byte SMiT2Sab) {
        this.SMiT2Sab = SMiT2Sab;
    }
    public Byte getEHhT1Dom() {
        return this.EHhT1Dom;
    }
    
    public void setEHhT1Dom(Byte EHhT1Dom) {
        this.EHhT1Dom = EHhT1Dom;
    }
    public Byte getEMiT1Dom() {
        return this.EMiT1Dom;
    }
    
    public void setEMiT1Dom(Byte EMiT1Dom) {
        this.EMiT1Dom = EMiT1Dom;
    }
    public Byte getSHhT1Dom() {
        return this.SHhT1Dom;
    }
    
    public void setSHhT1Dom(Byte SHhT1Dom) {
        this.SHhT1Dom = SHhT1Dom;
    }
    public Byte getSMiT1Dom() {
        return this.SMiT1Dom;
    }
    
    public void setSMiT1Dom(Byte SMiT1Dom) {
        this.SMiT1Dom = SMiT1Dom;
    }
    public Byte getEHhT2Dom() {
        return this.EHhT2Dom;
    }
    
    public void setEHhT2Dom(Byte EHhT2Dom) {
        this.EHhT2Dom = EHhT2Dom;
    }
    public Byte getEMiT2Dom() {
        return this.EMiT2Dom;
    }
    
    public void setEMiT2Dom(Byte EMiT2Dom) {
        this.EMiT2Dom = EMiT2Dom;
    }
    public Byte getSHhT2Dom() {
        return this.SHhT2Dom;
    }
    
    public void setSHhT2Dom(Byte SHhT2Dom) {
        this.SHhT2Dom = SHhT2Dom;
    }
    public Byte getSMiT2Dom() {
        return this.SMiT2Dom;
    }
    
    public void setSMiT2Dom(Byte SMiT2Dom) {
        this.SMiT2Dom = SMiT2Dom;
    }
    public Boolean getIndPermiteFeriado() {
        return this.indPermiteFeriado;
    }
    
    public void setIndPermiteFeriado(Boolean indPermiteFeriado) {
        this.indPermiteFeriado = indPermiteFeriado;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public Short getMiToleranciaExpediente() {
        return this.miToleranciaExpediente;
    }
    
    public void setMiToleranciaExpediente(Short miToleranciaExpediente) {
        this.miToleranciaExpediente = miToleranciaExpediente;
    }
    public Set getJrcUsuarios() {
        return this.jrcUsuarios;
    }
    
    public void setJrcUsuarios(Set jrcUsuarios) {
        this.jrcUsuarios = jrcUsuarios;
    }




}


