package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcImpressora generated by hbm2java
 */
public class JrcImpressora  implements java.io.Serializable {


     private long idImpressora;
     private JrcEmpresa jrcEmpresa;
     private JrcLoja jrcLoja;
     private JrcModeloImpressora jrcModeloImpressora;
     private JrcUsuario jrcUsuario;
     private String descricao;
     private String mapeamento;
     private boolean indAtivo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private Set jrcPdvs = new HashSet(0);

    public JrcImpressora() {
    }

	
    public JrcImpressora(long idImpressora, JrcEmpresa jrcEmpresa, JrcLoja jrcLoja, JrcModeloImpressora jrcModeloImpressora, JrcUsuario jrcUsuario, String descricao, String mapeamento, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idImpressora = idImpressora;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcLoja = jrcLoja;
        this.jrcModeloImpressora = jrcModeloImpressora;
        this.jrcUsuario = jrcUsuario;
        this.descricao = descricao;
        this.mapeamento = mapeamento;
        this.indAtivo = indAtivo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcImpressora(long idImpressora, JrcEmpresa jrcEmpresa, JrcLoja jrcLoja, JrcModeloImpressora jrcModeloImpressora, JrcUsuario jrcUsuario, String descricao, String mapeamento, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, Set jrcPdvs) {
       this.idImpressora = idImpressora;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcLoja = jrcLoja;
       this.jrcModeloImpressora = jrcModeloImpressora;
       this.jrcUsuario = jrcUsuario;
       this.descricao = descricao;
       this.mapeamento = mapeamento;
       this.indAtivo = indAtivo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.jrcPdvs = jrcPdvs;
    }
   
    public long getIdImpressora() {
        return this.idImpressora;
    }
    
    public void setIdImpressora(long idImpressora) {
        this.idImpressora = idImpressora;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcLoja getJrcLoja() {
        return this.jrcLoja;
    }
    
    public void setJrcLoja(JrcLoja jrcLoja) {
        this.jrcLoja = jrcLoja;
    }
    public JrcModeloImpressora getJrcModeloImpressora() {
        return this.jrcModeloImpressora;
    }
    
    public void setJrcModeloImpressora(JrcModeloImpressora jrcModeloImpressora) {
        this.jrcModeloImpressora = jrcModeloImpressora;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getMapeamento() {
        return this.mapeamento;
    }
    
    public void setMapeamento(String mapeamento) {
        this.mapeamento = mapeamento;
    }
    public boolean isIndAtivo() {
        return this.indAtivo;
    }
    
    public void setIndAtivo(boolean indAtivo) {
        this.indAtivo = indAtivo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public Set getJrcPdvs() {
        return this.jrcPdvs;
    }
    
    public void setJrcPdvs(Set jrcPdvs) {
        this.jrcPdvs = jrcPdvs;
    }




}


