package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcKit generated by hbm2java
 */
public class JrcKit  implements java.io.Serializable {


     private long idKit;
     private JrcEmpresa jrcEmpresa;
     private JrcStatusProduto jrcStatusProduto;
     private JrcUnidade jrcUnidade;
     private JrcUsuario jrcUsuarioByIdUsuarioAprovou;
     private JrcUsuario jrcUsuarioByIdUsuarioReg;
     private String codigo;
     private String descricao;
     private boolean indSaidaLoja;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String codigoRef;
     private String flagIat;
     private String flagIppt;
     private Set jrcPedidoVendaItems = new HashSet(0);
     private Set jrcPromocaoItemDetalhes = new HashSet(0);

    public JrcKit() {
    }

	
    public JrcKit(long idKit, JrcEmpresa jrcEmpresa, JrcStatusProduto jrcStatusProduto, JrcUnidade jrcUnidade, JrcUsuario jrcUsuarioByIdUsuarioReg, String codigo, String descricao, boolean indSaidaLoja, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String flagIat, String flagIppt) {
        this.idKit = idKit;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcStatusProduto = jrcStatusProduto;
        this.jrcUnidade = jrcUnidade;
        this.jrcUsuarioByIdUsuarioReg = jrcUsuarioByIdUsuarioReg;
        this.codigo = codigo;
        this.descricao = descricao;
        this.indSaidaLoja = indSaidaLoja;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.flagIat = flagIat;
        this.flagIppt = flagIppt;
    }
    public JrcKit(long idKit, JrcEmpresa jrcEmpresa, JrcStatusProduto jrcStatusProduto, JrcUnidade jrcUnidade, JrcUsuario jrcUsuarioByIdUsuarioAprovou, JrcUsuario jrcUsuarioByIdUsuarioReg, String codigo, String descricao, boolean indSaidaLoja, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String codigoRef, String flagIat, String flagIppt, Set jrcPedidoVendaItems, Set jrcPromocaoItemDetalhes) {
       this.idKit = idKit;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcStatusProduto = jrcStatusProduto;
       this.jrcUnidade = jrcUnidade;
       this.jrcUsuarioByIdUsuarioAprovou = jrcUsuarioByIdUsuarioAprovou;
       this.jrcUsuarioByIdUsuarioReg = jrcUsuarioByIdUsuarioReg;
       this.codigo = codigo;
       this.descricao = descricao;
       this.indSaidaLoja = indSaidaLoja;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.codigoRef = codigoRef;
       this.flagIat = flagIat;
       this.flagIppt = flagIppt;
       this.jrcPedidoVendaItems = jrcPedidoVendaItems;
       this.jrcPromocaoItemDetalhes = jrcPromocaoItemDetalhes;
    }
   
    public long getIdKit() {
        return this.idKit;
    }
    
    public void setIdKit(long idKit) {
        this.idKit = idKit;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcStatusProduto getJrcStatusProduto() {
        return this.jrcStatusProduto;
    }
    
    public void setJrcStatusProduto(JrcStatusProduto jrcStatusProduto) {
        this.jrcStatusProduto = jrcStatusProduto;
    }
    public JrcUnidade getJrcUnidade() {
        return this.jrcUnidade;
    }
    
    public void setJrcUnidade(JrcUnidade jrcUnidade) {
        this.jrcUnidade = jrcUnidade;
    }
    public JrcUsuario getJrcUsuarioByIdUsuarioAprovou() {
        return this.jrcUsuarioByIdUsuarioAprovou;
    }
    
    public void setJrcUsuarioByIdUsuarioAprovou(JrcUsuario jrcUsuarioByIdUsuarioAprovou) {
        this.jrcUsuarioByIdUsuarioAprovou = jrcUsuarioByIdUsuarioAprovou;
    }
    public JrcUsuario getJrcUsuarioByIdUsuarioReg() {
        return this.jrcUsuarioByIdUsuarioReg;
    }
    
    public void setJrcUsuarioByIdUsuarioReg(JrcUsuario jrcUsuarioByIdUsuarioReg) {
        this.jrcUsuarioByIdUsuarioReg = jrcUsuarioByIdUsuarioReg;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public boolean isIndSaidaLoja() {
        return this.indSaidaLoja;
    }
    
    public void setIndSaidaLoja(boolean indSaidaLoja) {
        this.indSaidaLoja = indSaidaLoja;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getCodigoRef() {
        return this.codigoRef;
    }
    
    public void setCodigoRef(String codigoRef) {
        this.codigoRef = codigoRef;
    }
    public String getFlagIat() {
        return this.flagIat;
    }
    
    public void setFlagIat(String flagIat) {
        this.flagIat = flagIat;
    }
    public String getFlagIppt() {
        return this.flagIppt;
    }
    
    public void setFlagIppt(String flagIppt) {
        this.flagIppt = flagIppt;
    }
    public Set getJrcPedidoVendaItems() {
        return this.jrcPedidoVendaItems;
    }
    
    public void setJrcPedidoVendaItems(Set jrcPedidoVendaItems) {
        this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }
    public Set getJrcPromocaoItemDetalhes() {
        return this.jrcPromocaoItemDetalhes;
    }
    
    public void setJrcPromocaoItemDetalhes(Set jrcPromocaoItemDetalhes) {
        this.jrcPromocaoItemDetalhes = jrcPromocaoItemDetalhes;
    }




}


