package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcLoteNfe generated by hbm2java
 */
public class JrcLoteNfe  implements java.io.Serializable {


     private long idLoteNfe;
     private JrcEmpresa jrcEmpresa;
     private JrcLoja jrcLoja;
     private JrcUf jrcUf;
     private JrcUsuario jrcUsuario;
     private String versaoLayout;
     private String flagTipoAmbiente;
     private String versaoAplicacao;
     private String flagStatus;
     private Short codStatus;
     private String descStatus;
     private Date dtRecbto;
     private Long nroRecibo;
     private Short codMsg;
     private String descMsg;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String flagAppRef;
     private String codigoRef;
     private String descricaoRef;
     private String dpecVersaoLayout;
     private String dpecVersaoAplicacao;
     private String dpecFlagStatus;
     private Short dpecCodStatus;
     private String dpecDescStatus;
     private Date dpecDtRecbto;
     private Long dpecNroRecibo;
     private Boolean indNfc;
     private Set jrcNotaFiscals = new HashSet(0);

    public JrcLoteNfe() {
    }

	
    public JrcLoteNfe(long idLoteNfe, JrcEmpresa jrcEmpresa, String versaoLayout, String flagTipoAmbiente, String flagStatus, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idLoteNfe = idLoteNfe;
        this.jrcEmpresa = jrcEmpresa;
        this.versaoLayout = versaoLayout;
        this.flagTipoAmbiente = flagTipoAmbiente;
        this.flagStatus = flagStatus;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcLoteNfe(long idLoteNfe, JrcEmpresa jrcEmpresa, JrcLoja jrcLoja, JrcUf jrcUf, JrcUsuario jrcUsuario, String versaoLayout, String flagTipoAmbiente, String versaoAplicacao, String flagStatus, Short codStatus, String descStatus, Date dtRecbto, Long nroRecibo, Short codMsg, String descMsg, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String flagAppRef, String codigoRef, String descricaoRef, String dpecVersaoLayout, String dpecVersaoAplicacao, String dpecFlagStatus, Short dpecCodStatus, String dpecDescStatus, Date dpecDtRecbto, Long dpecNroRecibo, Boolean indNfc, Set jrcNotaFiscals) {
       this.idLoteNfe = idLoteNfe;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcLoja = jrcLoja;
       this.jrcUf = jrcUf;
       this.jrcUsuario = jrcUsuario;
       this.versaoLayout = versaoLayout;
       this.flagTipoAmbiente = flagTipoAmbiente;
       this.versaoAplicacao = versaoAplicacao;
       this.flagStatus = flagStatus;
       this.codStatus = codStatus;
       this.descStatus = descStatus;
       this.dtRecbto = dtRecbto;
       this.nroRecibo = nroRecibo;
       this.codMsg = codMsg;
       this.descMsg = descMsg;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.flagAppRef = flagAppRef;
       this.codigoRef = codigoRef;
       this.descricaoRef = descricaoRef;
       this.dpecVersaoLayout = dpecVersaoLayout;
       this.dpecVersaoAplicacao = dpecVersaoAplicacao;
       this.dpecFlagStatus = dpecFlagStatus;
       this.dpecCodStatus = dpecCodStatus;
       this.dpecDescStatus = dpecDescStatus;
       this.dpecDtRecbto = dpecDtRecbto;
       this.dpecNroRecibo = dpecNroRecibo;
       this.indNfc = indNfc;
       this.jrcNotaFiscals = jrcNotaFiscals;
    }
   
    public long getIdLoteNfe() {
        return this.idLoteNfe;
    }
    
    public void setIdLoteNfe(long idLoteNfe) {
        this.idLoteNfe = idLoteNfe;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcLoja getJrcLoja() {
        return this.jrcLoja;
    }
    
    public void setJrcLoja(JrcLoja jrcLoja) {
        this.jrcLoja = jrcLoja;
    }
    public JrcUf getJrcUf() {
        return this.jrcUf;
    }
    
    public void setJrcUf(JrcUf jrcUf) {
        this.jrcUf = jrcUf;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getVersaoLayout() {
        return this.versaoLayout;
    }
    
    public void setVersaoLayout(String versaoLayout) {
        this.versaoLayout = versaoLayout;
    }
    public String getFlagTipoAmbiente() {
        return this.flagTipoAmbiente;
    }
    
    public void setFlagTipoAmbiente(String flagTipoAmbiente) {
        this.flagTipoAmbiente = flagTipoAmbiente;
    }
    public String getVersaoAplicacao() {
        return this.versaoAplicacao;
    }
    
    public void setVersaoAplicacao(String versaoAplicacao) {
        this.versaoAplicacao = versaoAplicacao;
    }
    public String getFlagStatus() {
        return this.flagStatus;
    }
    
    public void setFlagStatus(String flagStatus) {
        this.flagStatus = flagStatus;
    }
    public Short getCodStatus() {
        return this.codStatus;
    }
    
    public void setCodStatus(Short codStatus) {
        this.codStatus = codStatus;
    }
    public String getDescStatus() {
        return this.descStatus;
    }
    
    public void setDescStatus(String descStatus) {
        this.descStatus = descStatus;
    }
    public Date getDtRecbto() {
        return this.dtRecbto;
    }
    
    public void setDtRecbto(Date dtRecbto) {
        this.dtRecbto = dtRecbto;
    }
    public Long getNroRecibo() {
        return this.nroRecibo;
    }
    
    public void setNroRecibo(Long nroRecibo) {
        this.nroRecibo = nroRecibo;
    }
    public Short getCodMsg() {
        return this.codMsg;
    }
    
    public void setCodMsg(Short codMsg) {
        this.codMsg = codMsg;
    }
    public String getDescMsg() {
        return this.descMsg;
    }
    
    public void setDescMsg(String descMsg) {
        this.descMsg = descMsg;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getFlagAppRef() {
        return this.flagAppRef;
    }
    
    public void setFlagAppRef(String flagAppRef) {
        this.flagAppRef = flagAppRef;
    }
    public String getCodigoRef() {
        return this.codigoRef;
    }
    
    public void setCodigoRef(String codigoRef) {
        this.codigoRef = codigoRef;
    }
    public String getDescricaoRef() {
        return this.descricaoRef;
    }
    
    public void setDescricaoRef(String descricaoRef) {
        this.descricaoRef = descricaoRef;
    }
    public String getDpecVersaoLayout() {
        return this.dpecVersaoLayout;
    }
    
    public void setDpecVersaoLayout(String dpecVersaoLayout) {
        this.dpecVersaoLayout = dpecVersaoLayout;
    }
    public String getDpecVersaoAplicacao() {
        return this.dpecVersaoAplicacao;
    }
    
    public void setDpecVersaoAplicacao(String dpecVersaoAplicacao) {
        this.dpecVersaoAplicacao = dpecVersaoAplicacao;
    }
    public String getDpecFlagStatus() {
        return this.dpecFlagStatus;
    }
    
    public void setDpecFlagStatus(String dpecFlagStatus) {
        this.dpecFlagStatus = dpecFlagStatus;
    }
    public Short getDpecCodStatus() {
        return this.dpecCodStatus;
    }
    
    public void setDpecCodStatus(Short dpecCodStatus) {
        this.dpecCodStatus = dpecCodStatus;
    }
    public String getDpecDescStatus() {
        return this.dpecDescStatus;
    }
    
    public void setDpecDescStatus(String dpecDescStatus) {
        this.dpecDescStatus = dpecDescStatus;
    }
    public Date getDpecDtRecbto() {
        return this.dpecDtRecbto;
    }
    
    public void setDpecDtRecbto(Date dpecDtRecbto) {
        this.dpecDtRecbto = dpecDtRecbto;
    }
    public Long getDpecNroRecibo() {
        return this.dpecNroRecibo;
    }
    
    public void setDpecNroRecibo(Long dpecNroRecibo) {
        this.dpecNroRecibo = dpecNroRecibo;
    }
    public Boolean getIndNfc() {
        return this.indNfc;
    }
    
    public void setIndNfc(Boolean indNfc) {
        this.indNfc = indNfc;
    }
    public Set getJrcNotaFiscals() {
        return this.jrcNotaFiscals;
    }
    
    public void setJrcNotaFiscals(Set jrcNotaFiscals) {
        this.jrcNotaFiscals = jrcNotaFiscals;
    }




}


