package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcMensagemAnalise generated by hbm2java
 */
public class JrcMensagemAnalise  implements java.io.Serializable {


     private long idMensagemAnalise;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String mensagem;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String flagMensagemAnalise;
     private Boolean indMsgDataprev;
     private String codigoRef;
     private Set jrcPedidoVendas = new HashSet(0);

    public JrcMensagemAnalise() {
    }

	
    public JrcMensagemAnalise(long idMensagemAnalise, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String mensagem, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String flagMensagemAnalise) {
        this.idMensagemAnalise = idMensagemAnalise;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.mensagem = mensagem;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.flagMensagemAnalise = flagMensagemAnalise;
    }
    public JrcMensagemAnalise(long idMensagemAnalise, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String mensagem, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String flagMensagemAnalise, Boolean indMsgDataprev, String codigoRef, Set jrcPedidoVendas) {
       this.idMensagemAnalise = idMensagemAnalise;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.mensagem = mensagem;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.flagMensagemAnalise = flagMensagemAnalise;
       this.indMsgDataprev = indMsgDataprev;
       this.codigoRef = codigoRef;
       this.jrcPedidoVendas = jrcPedidoVendas;
    }
   
    public long getIdMensagemAnalise() {
        return this.idMensagemAnalise;
    }
    
    public void setIdMensagemAnalise(long idMensagemAnalise) {
        this.idMensagemAnalise = idMensagemAnalise;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getFlagMensagemAnalise() {
        return this.flagMensagemAnalise;
    }
    
    public void setFlagMensagemAnalise(String flagMensagemAnalise) {
        this.flagMensagemAnalise = flagMensagemAnalise;
    }
    public Boolean getIndMsgDataprev() {
        return this.indMsgDataprev;
    }
    
    public void setIndMsgDataprev(Boolean indMsgDataprev) {
        this.indMsgDataprev = indMsgDataprev;
    }
    public String getCodigoRef() {
        return this.codigoRef;
    }
    
    public void setCodigoRef(String codigoRef) {
        this.codigoRef = codigoRef;
    }
    public Set getJrcPedidoVendas() {
        return this.jrcPedidoVendas;
    }
    
    public void setJrcPedidoVendas(Set jrcPedidoVendas) {
        this.jrcPedidoVendas = jrcPedidoVendas;
    }




}


