package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcModeloEcf generated by hbm2java
 */
public class JrcModeloEcf  implements java.io.Serializable {


     private long idModeloEcf;
     private JrcEmpresa jrcEmpresa;
     private JrcFabricante jrcFabricante;
     private JrcMarca jrcMarca;
     private JrcTipoEcf jrcTipoEcf;
     private JrcUsuario jrcUsuario;
     private String descBreve;
     private String descLonga;
     private String cnie;
     private short maxItensPorCupom;
     private boolean indMfd;
     private boolean indGuilhotina;
     private boolean indCupomAdicional;
     private boolean indEstornoFormaPagto;
     private boolean indAutentica;
     private boolean indCmc7;
     private boolean indCodigoBarra;
     private boolean indCheque;
     private boolean indCupomNaoFiscal;
     private boolean indCcd;
     private boolean indBilhetePassagem;
     private boolean indPrestadorServicoDif;
     private boolean indLogoCabecalho;
     private boolean indCancItem;
     private boolean indCancCupomEmitido;
     private boolean indCancCupomEmEmissao;
     private boolean indCancCupomNaoFiscal;
     private boolean indAcrescimoItem;
     private boolean indAcrescimoSubtotal;
     private boolean indAcrescimoCupomNaoFiscal;
     private boolean indDescontoItem;
     private boolean indDecontoSubtotal;
     private boolean indDescontoCupomNaoFiscal;
     private boolean indAtivo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String hash1;
     private String flagEcf;
     private Set jrcEcfs = new HashSet(0);

    public JrcModeloEcf() {
    }

	
    public JrcModeloEcf(long idModeloEcf, JrcEmpresa jrcEmpresa, JrcFabricante jrcFabricante, JrcMarca jrcMarca, JrcTipoEcf jrcTipoEcf, JrcUsuario jrcUsuario, String descBreve, String cnie, short maxItensPorCupom, boolean indMfd, boolean indGuilhotina, boolean indCupomAdicional, boolean indEstornoFormaPagto, boolean indAutentica, boolean indCmc7, boolean indCodigoBarra, boolean indCheque, boolean indCupomNaoFiscal, boolean indCcd, boolean indBilhetePassagem, boolean indPrestadorServicoDif, boolean indLogoCabecalho, boolean indCancItem, boolean indCancCupomEmitido, boolean indCancCupomEmEmissao, boolean indCancCupomNaoFiscal, boolean indAcrescimoItem, boolean indAcrescimoSubtotal, boolean indAcrescimoCupomNaoFiscal, boolean indDescontoItem, boolean indDecontoSubtotal, boolean indDescontoCupomNaoFiscal, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String flagEcf) {
        this.idModeloEcf = idModeloEcf;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcFabricante = jrcFabricante;
        this.jrcMarca = jrcMarca;
        this.jrcTipoEcf = jrcTipoEcf;
        this.jrcUsuario = jrcUsuario;
        this.descBreve = descBreve;
        this.cnie = cnie;
        this.maxItensPorCupom = maxItensPorCupom;
        this.indMfd = indMfd;
        this.indGuilhotina = indGuilhotina;
        this.indCupomAdicional = indCupomAdicional;
        this.indEstornoFormaPagto = indEstornoFormaPagto;
        this.indAutentica = indAutentica;
        this.indCmc7 = indCmc7;
        this.indCodigoBarra = indCodigoBarra;
        this.indCheque = indCheque;
        this.indCupomNaoFiscal = indCupomNaoFiscal;
        this.indCcd = indCcd;
        this.indBilhetePassagem = indBilhetePassagem;
        this.indPrestadorServicoDif = indPrestadorServicoDif;
        this.indLogoCabecalho = indLogoCabecalho;
        this.indCancItem = indCancItem;
        this.indCancCupomEmitido = indCancCupomEmitido;
        this.indCancCupomEmEmissao = indCancCupomEmEmissao;
        this.indCancCupomNaoFiscal = indCancCupomNaoFiscal;
        this.indAcrescimoItem = indAcrescimoItem;
        this.indAcrescimoSubtotal = indAcrescimoSubtotal;
        this.indAcrescimoCupomNaoFiscal = indAcrescimoCupomNaoFiscal;
        this.indDescontoItem = indDescontoItem;
        this.indDecontoSubtotal = indDecontoSubtotal;
        this.indDescontoCupomNaoFiscal = indDescontoCupomNaoFiscal;
        this.indAtivo = indAtivo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.flagEcf = flagEcf;
    }
    public JrcModeloEcf(long idModeloEcf, JrcEmpresa jrcEmpresa, JrcFabricante jrcFabricante, JrcMarca jrcMarca, JrcTipoEcf jrcTipoEcf, JrcUsuario jrcUsuario, String descBreve, String descLonga, String cnie, short maxItensPorCupom, boolean indMfd, boolean indGuilhotina, boolean indCupomAdicional, boolean indEstornoFormaPagto, boolean indAutentica, boolean indCmc7, boolean indCodigoBarra, boolean indCheque, boolean indCupomNaoFiscal, boolean indCcd, boolean indBilhetePassagem, boolean indPrestadorServicoDif, boolean indLogoCabecalho, boolean indCancItem, boolean indCancCupomEmitido, boolean indCancCupomEmEmissao, boolean indCancCupomNaoFiscal, boolean indAcrescimoItem, boolean indAcrescimoSubtotal, boolean indAcrescimoCupomNaoFiscal, boolean indDescontoItem, boolean indDecontoSubtotal, boolean indDescontoCupomNaoFiscal, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String hash1, String flagEcf, Set jrcEcfs) {
       this.idModeloEcf = idModeloEcf;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcFabricante = jrcFabricante;
       this.jrcMarca = jrcMarca;
       this.jrcTipoEcf = jrcTipoEcf;
       this.jrcUsuario = jrcUsuario;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.cnie = cnie;
       this.maxItensPorCupom = maxItensPorCupom;
       this.indMfd = indMfd;
       this.indGuilhotina = indGuilhotina;
       this.indCupomAdicional = indCupomAdicional;
       this.indEstornoFormaPagto = indEstornoFormaPagto;
       this.indAutentica = indAutentica;
       this.indCmc7 = indCmc7;
       this.indCodigoBarra = indCodigoBarra;
       this.indCheque = indCheque;
       this.indCupomNaoFiscal = indCupomNaoFiscal;
       this.indCcd = indCcd;
       this.indBilhetePassagem = indBilhetePassagem;
       this.indPrestadorServicoDif = indPrestadorServicoDif;
       this.indLogoCabecalho = indLogoCabecalho;
       this.indCancItem = indCancItem;
       this.indCancCupomEmitido = indCancCupomEmitido;
       this.indCancCupomEmEmissao = indCancCupomEmEmissao;
       this.indCancCupomNaoFiscal = indCancCupomNaoFiscal;
       this.indAcrescimoItem = indAcrescimoItem;
       this.indAcrescimoSubtotal = indAcrescimoSubtotal;
       this.indAcrescimoCupomNaoFiscal = indAcrescimoCupomNaoFiscal;
       this.indDescontoItem = indDescontoItem;
       this.indDecontoSubtotal = indDecontoSubtotal;
       this.indDescontoCupomNaoFiscal = indDescontoCupomNaoFiscal;
       this.indAtivo = indAtivo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.hash1 = hash1;
       this.flagEcf = flagEcf;
       this.jrcEcfs = jrcEcfs;
    }
   
    public long getIdModeloEcf() {
        return this.idModeloEcf;
    }
    
    public void setIdModeloEcf(long idModeloEcf) {
        this.idModeloEcf = idModeloEcf;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcFabricante getJrcFabricante() {
        return this.jrcFabricante;
    }
    
    public void setJrcFabricante(JrcFabricante jrcFabricante) {
        this.jrcFabricante = jrcFabricante;
    }
    public JrcMarca getJrcMarca() {
        return this.jrcMarca;
    }
    
    public void setJrcMarca(JrcMarca jrcMarca) {
        this.jrcMarca = jrcMarca;
    }
    public JrcTipoEcf getJrcTipoEcf() {
        return this.jrcTipoEcf;
    }
    
    public void setJrcTipoEcf(JrcTipoEcf jrcTipoEcf) {
        this.jrcTipoEcf = jrcTipoEcf;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public String getCnie() {
        return this.cnie;
    }
    
    public void setCnie(String cnie) {
        this.cnie = cnie;
    }
    public short getMaxItensPorCupom() {
        return this.maxItensPorCupom;
    }
    
    public void setMaxItensPorCupom(short maxItensPorCupom) {
        this.maxItensPorCupom = maxItensPorCupom;
    }
    public boolean isIndMfd() {
        return this.indMfd;
    }
    
    public void setIndMfd(boolean indMfd) {
        this.indMfd = indMfd;
    }
    public boolean isIndGuilhotina() {
        return this.indGuilhotina;
    }
    
    public void setIndGuilhotina(boolean indGuilhotina) {
        this.indGuilhotina = indGuilhotina;
    }
    public boolean isIndCupomAdicional() {
        return this.indCupomAdicional;
    }
    
    public void setIndCupomAdicional(boolean indCupomAdicional) {
        this.indCupomAdicional = indCupomAdicional;
    }
    public boolean isIndEstornoFormaPagto() {
        return this.indEstornoFormaPagto;
    }
    
    public void setIndEstornoFormaPagto(boolean indEstornoFormaPagto) {
        this.indEstornoFormaPagto = indEstornoFormaPagto;
    }
    public boolean isIndAutentica() {
        return this.indAutentica;
    }
    
    public void setIndAutentica(boolean indAutentica) {
        this.indAutentica = indAutentica;
    }
    public boolean isIndCmc7() {
        return this.indCmc7;
    }
    
    public void setIndCmc7(boolean indCmc7) {
        this.indCmc7 = indCmc7;
    }
    public boolean isIndCodigoBarra() {
        return this.indCodigoBarra;
    }
    
    public void setIndCodigoBarra(boolean indCodigoBarra) {
        this.indCodigoBarra = indCodigoBarra;
    }
    public boolean isIndCheque() {
        return this.indCheque;
    }
    
    public void setIndCheque(boolean indCheque) {
        this.indCheque = indCheque;
    }
    public boolean isIndCupomNaoFiscal() {
        return this.indCupomNaoFiscal;
    }
    
    public void setIndCupomNaoFiscal(boolean indCupomNaoFiscal) {
        this.indCupomNaoFiscal = indCupomNaoFiscal;
    }
    public boolean isIndCcd() {
        return this.indCcd;
    }
    
    public void setIndCcd(boolean indCcd) {
        this.indCcd = indCcd;
    }
    public boolean isIndBilhetePassagem() {
        return this.indBilhetePassagem;
    }
    
    public void setIndBilhetePassagem(boolean indBilhetePassagem) {
        this.indBilhetePassagem = indBilhetePassagem;
    }
    public boolean isIndPrestadorServicoDif() {
        return this.indPrestadorServicoDif;
    }
    
    public void setIndPrestadorServicoDif(boolean indPrestadorServicoDif) {
        this.indPrestadorServicoDif = indPrestadorServicoDif;
    }
    public boolean isIndLogoCabecalho() {
        return this.indLogoCabecalho;
    }
    
    public void setIndLogoCabecalho(boolean indLogoCabecalho) {
        this.indLogoCabecalho = indLogoCabecalho;
    }
    public boolean isIndCancItem() {
        return this.indCancItem;
    }
    
    public void setIndCancItem(boolean indCancItem) {
        this.indCancItem = indCancItem;
    }
    public boolean isIndCancCupomEmitido() {
        return this.indCancCupomEmitido;
    }
    
    public void setIndCancCupomEmitido(boolean indCancCupomEmitido) {
        this.indCancCupomEmitido = indCancCupomEmitido;
    }
    public boolean isIndCancCupomEmEmissao() {
        return this.indCancCupomEmEmissao;
    }
    
    public void setIndCancCupomEmEmissao(boolean indCancCupomEmEmissao) {
        this.indCancCupomEmEmissao = indCancCupomEmEmissao;
    }
    public boolean isIndCancCupomNaoFiscal() {
        return this.indCancCupomNaoFiscal;
    }
    
    public void setIndCancCupomNaoFiscal(boolean indCancCupomNaoFiscal) {
        this.indCancCupomNaoFiscal = indCancCupomNaoFiscal;
    }
    public boolean isIndAcrescimoItem() {
        return this.indAcrescimoItem;
    }
    
    public void setIndAcrescimoItem(boolean indAcrescimoItem) {
        this.indAcrescimoItem = indAcrescimoItem;
    }
    public boolean isIndAcrescimoSubtotal() {
        return this.indAcrescimoSubtotal;
    }
    
    public void setIndAcrescimoSubtotal(boolean indAcrescimoSubtotal) {
        this.indAcrescimoSubtotal = indAcrescimoSubtotal;
    }
    public boolean isIndAcrescimoCupomNaoFiscal() {
        return this.indAcrescimoCupomNaoFiscal;
    }
    
    public void setIndAcrescimoCupomNaoFiscal(boolean indAcrescimoCupomNaoFiscal) {
        this.indAcrescimoCupomNaoFiscal = indAcrescimoCupomNaoFiscal;
    }
    public boolean isIndDescontoItem() {
        return this.indDescontoItem;
    }
    
    public void setIndDescontoItem(boolean indDescontoItem) {
        this.indDescontoItem = indDescontoItem;
    }
    public boolean isIndDecontoSubtotal() {
        return this.indDecontoSubtotal;
    }
    
    public void setIndDecontoSubtotal(boolean indDecontoSubtotal) {
        this.indDecontoSubtotal = indDecontoSubtotal;
    }
    public boolean isIndDescontoCupomNaoFiscal() {
        return this.indDescontoCupomNaoFiscal;
    }
    
    public void setIndDescontoCupomNaoFiscal(boolean indDescontoCupomNaoFiscal) {
        this.indDescontoCupomNaoFiscal = indDescontoCupomNaoFiscal;
    }
    public boolean isIndAtivo() {
        return this.indAtivo;
    }
    
    public void setIndAtivo(boolean indAtivo) {
        this.indAtivo = indAtivo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getHash1() {
        return this.hash1;
    }
    
    public void setHash1(String hash1) {
        this.hash1 = hash1;
    }
    public String getFlagEcf() {
        return this.flagEcf;
    }
    
    public void setFlagEcf(String flagEcf) {
        this.flagEcf = flagEcf;
    }
    public Set getJrcEcfs() {
        return this.jrcEcfs;
    }
    
    public void setJrcEcfs(Set jrcEcfs) {
        this.jrcEcfs = jrcEcfs;
    }




}


