package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcMovimentoEcf generated by hbm2java
 */
public class JrcMovimentoEcf  implements java.io.Serializable {


     private long idMovimentoEcf;
     private JrcEcfXPdv jrcEcfXPdv;
     private JrcEmpresa jrcEmpresa;
     private JrcMovimentoPdv jrcMovimentoPdv;
     private JrcPaf jrcPaf;
     private Date dtAbertura;
     private String operadorAbertura;
     private Date dtFechamento;
     private String operadorFechamento;
     private String flagRessalvaAbertura;
     private String flagRessalvaFechamento;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String hash1;
     private Set jrcLancamentoEcfCfs = new HashSet(0);

    public JrcMovimentoEcf() {
    }

	
    public JrcMovimentoEcf(long idMovimentoEcf, JrcEcfXPdv jrcEcfXPdv, JrcEmpresa jrcEmpresa, JrcMovimentoPdv jrcMovimentoPdv, JrcPaf jrcPaf, Date dtAbertura, String operadorAbertura, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idMovimentoEcf = idMovimentoEcf;
        this.jrcEcfXPdv = jrcEcfXPdv;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcMovimentoPdv = jrcMovimentoPdv;
        this.jrcPaf = jrcPaf;
        this.dtAbertura = dtAbertura;
        this.operadorAbertura = operadorAbertura;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcMovimentoEcf(long idMovimentoEcf, JrcEcfXPdv jrcEcfXPdv, JrcEmpresa jrcEmpresa, JrcMovimentoPdv jrcMovimentoPdv, JrcPaf jrcPaf, Date dtAbertura, String operadorAbertura, Date dtFechamento, String operadorFechamento, String flagRessalvaAbertura, String flagRessalvaFechamento, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String hash1, Set jrcLancamentoEcfCfs) {
       this.idMovimentoEcf = idMovimentoEcf;
       this.jrcEcfXPdv = jrcEcfXPdv;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcMovimentoPdv = jrcMovimentoPdv;
       this.jrcPaf = jrcPaf;
       this.dtAbertura = dtAbertura;
       this.operadorAbertura = operadorAbertura;
       this.dtFechamento = dtFechamento;
       this.operadorFechamento = operadorFechamento;
       this.flagRessalvaAbertura = flagRessalvaAbertura;
       this.flagRessalvaFechamento = flagRessalvaFechamento;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.hash1 = hash1;
       this.jrcLancamentoEcfCfs = jrcLancamentoEcfCfs;
    }
   
    public long getIdMovimentoEcf() {
        return this.idMovimentoEcf;
    }
    
    public void setIdMovimentoEcf(long idMovimentoEcf) {
        this.idMovimentoEcf = idMovimentoEcf;
    }
    public JrcEcfXPdv getJrcEcfXPdv() {
        return this.jrcEcfXPdv;
    }
    
    public void setJrcEcfXPdv(JrcEcfXPdv jrcEcfXPdv) {
        this.jrcEcfXPdv = jrcEcfXPdv;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcMovimentoPdv getJrcMovimentoPdv() {
        return this.jrcMovimentoPdv;
    }
    
    public void setJrcMovimentoPdv(JrcMovimentoPdv jrcMovimentoPdv) {
        this.jrcMovimentoPdv = jrcMovimentoPdv;
    }
    public JrcPaf getJrcPaf() {
        return this.jrcPaf;
    }
    
    public void setJrcPaf(JrcPaf jrcPaf) {
        this.jrcPaf = jrcPaf;
    }
    public Date getDtAbertura() {
        return this.dtAbertura;
    }
    
    public void setDtAbertura(Date dtAbertura) {
        this.dtAbertura = dtAbertura;
    }
    public String getOperadorAbertura() {
        return this.operadorAbertura;
    }
    
    public void setOperadorAbertura(String operadorAbertura) {
        this.operadorAbertura = operadorAbertura;
    }
    public Date getDtFechamento() {
        return this.dtFechamento;
    }
    
    public void setDtFechamento(Date dtFechamento) {
        this.dtFechamento = dtFechamento;
    }
    public String getOperadorFechamento() {
        return this.operadorFechamento;
    }
    
    public void setOperadorFechamento(String operadorFechamento) {
        this.operadorFechamento = operadorFechamento;
    }
    public String getFlagRessalvaAbertura() {
        return this.flagRessalvaAbertura;
    }
    
    public void setFlagRessalvaAbertura(String flagRessalvaAbertura) {
        this.flagRessalvaAbertura = flagRessalvaAbertura;
    }
    public String getFlagRessalvaFechamento() {
        return this.flagRessalvaFechamento;
    }
    
    public void setFlagRessalvaFechamento(String flagRessalvaFechamento) {
        this.flagRessalvaFechamento = flagRessalvaFechamento;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getHash1() {
        return this.hash1;
    }
    
    public void setHash1(String hash1) {
        this.hash1 = hash1;
    }
    public Set getJrcLancamentoEcfCfs() {
        return this.jrcLancamentoEcfCfs;
    }
    
    public void setJrcLancamentoEcfCfs(Set jrcLancamentoEcfCfs) {
        this.jrcLancamentoEcfCfs = jrcLancamentoEcfCfs;
    }




}


