package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcPaf generated by hbm2java
 */
public class JrcPaf  implements java.io.Serializable {


     private long idPaf;
     private JrcDesenvolvedora jrcDesenvolvedora;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String identificacao;
     private String nomeComercial;
     private String nroLaudo;
     private String versao;
     private String especificacaoRequisitos;
     private boolean indAtivo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String arqListaPafArquivo;
     private String md5ArqListaPafArquivo;
     private String hash1;
     private Set jrcMovimentoEcfs = new HashSet(0);
     private Set jrcEcfXPdvs = new HashSet(0);

    public JrcPaf() {
    }

	
    public JrcPaf(long idPaf, JrcDesenvolvedora jrcDesenvolvedora, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String identificacao, String nomeComercial, String nroLaudo, String versao, String especificacaoRequisitos, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String arqListaPafArquivo, String md5ArqListaPafArquivo) {
        this.idPaf = idPaf;
        this.jrcDesenvolvedora = jrcDesenvolvedora;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.identificacao = identificacao;
        this.nomeComercial = nomeComercial;
        this.nroLaudo = nroLaudo;
        this.versao = versao;
        this.especificacaoRequisitos = especificacaoRequisitos;
        this.indAtivo = indAtivo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.arqListaPafArquivo = arqListaPafArquivo;
        this.md5ArqListaPafArquivo = md5ArqListaPafArquivo;
    }
    public JrcPaf(long idPaf, JrcDesenvolvedora jrcDesenvolvedora, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String identificacao, String nomeComercial, String nroLaudo, String versao, String especificacaoRequisitos, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String arqListaPafArquivo, String md5ArqListaPafArquivo, String hash1, Set jrcMovimentoEcfs, Set jrcEcfXPdvs) {
       this.idPaf = idPaf;
       this.jrcDesenvolvedora = jrcDesenvolvedora;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.identificacao = identificacao;
       this.nomeComercial = nomeComercial;
       this.nroLaudo = nroLaudo;
       this.versao = versao;
       this.especificacaoRequisitos = especificacaoRequisitos;
       this.indAtivo = indAtivo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.arqListaPafArquivo = arqListaPafArquivo;
       this.md5ArqListaPafArquivo = md5ArqListaPafArquivo;
       this.hash1 = hash1;
       this.jrcMovimentoEcfs = jrcMovimentoEcfs;
       this.jrcEcfXPdvs = jrcEcfXPdvs;
    }
   
    public long getIdPaf() {
        return this.idPaf;
    }
    
    public void setIdPaf(long idPaf) {
        this.idPaf = idPaf;
    }
    public JrcDesenvolvedora getJrcDesenvolvedora() {
        return this.jrcDesenvolvedora;
    }
    
    public void setJrcDesenvolvedora(JrcDesenvolvedora jrcDesenvolvedora) {
        this.jrcDesenvolvedora = jrcDesenvolvedora;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getIdentificacao() {
        return this.identificacao;
    }
    
    public void setIdentificacao(String identificacao) {
        this.identificacao = identificacao;
    }
    public String getNomeComercial() {
        return this.nomeComercial;
    }
    
    public void setNomeComercial(String nomeComercial) {
        this.nomeComercial = nomeComercial;
    }
    public String getNroLaudo() {
        return this.nroLaudo;
    }
    
    public void setNroLaudo(String nroLaudo) {
        this.nroLaudo = nroLaudo;
    }
    public String getVersao() {
        return this.versao;
    }
    
    public void setVersao(String versao) {
        this.versao = versao;
    }
    public String getEspecificacaoRequisitos() {
        return this.especificacaoRequisitos;
    }
    
    public void setEspecificacaoRequisitos(String especificacaoRequisitos) {
        this.especificacaoRequisitos = especificacaoRequisitos;
    }
    public boolean isIndAtivo() {
        return this.indAtivo;
    }
    
    public void setIndAtivo(boolean indAtivo) {
        this.indAtivo = indAtivo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getArqListaPafArquivo() {
        return this.arqListaPafArquivo;
    }
    
    public void setArqListaPafArquivo(String arqListaPafArquivo) {
        this.arqListaPafArquivo = arqListaPafArquivo;
    }
    public String getMd5ArqListaPafArquivo() {
        return this.md5ArqListaPafArquivo;
    }
    
    public void setMd5ArqListaPafArquivo(String md5ArqListaPafArquivo) {
        this.md5ArqListaPafArquivo = md5ArqListaPafArquivo;
    }
    public String getHash1() {
        return this.hash1;
    }
    
    public void setHash1(String hash1) {
        this.hash1 = hash1;
    }
    public Set getJrcMovimentoEcfs() {
        return this.jrcMovimentoEcfs;
    }
    
    public void setJrcMovimentoEcfs(Set jrcMovimentoEcfs) {
        this.jrcMovimentoEcfs = jrcMovimentoEcfs;
    }
    public Set getJrcEcfXPdvs() {
        return this.jrcEcfXPdvs;
    }
    
    public void setJrcEcfXPdvs(Set jrcEcfXPdvs) {
        this.jrcEcfXPdvs = jrcEcfXPdvs;
    }




}


