package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcPromocaoItemDetalhe generated by hbm2java
 */
public class JrcPromocaoItemDetalhe  implements java.io.Serializable {


     private JrcPromocaoItemDetalheId id;
     private JrcEmpresa jrcEmpresa;
     private JrcEqualizacaoItem jrcEqualizacaoItem;
     private JrcKit jrcKit;
     private JrcProduto jrcProduto;
     private JrcPromocaoItem jrcPromocaoItem;
     private JrcServicoPreco jrcServicoPreco;
     private String flagTipoItem;
     private Integer ctKit;
     private BigDecimal qtde;
     private BigDecimal precoPartida;
     private BigDecimal custoLiquido;
     private BigDecimal custoBruto;
     private BigDecimal equalizacao;
     private BigDecimal impostosEqEpd;
     private BigDecimal impostosEqSpf;
     private BigDecimal impostosEqSpd;
     private BigDecimal custoLiquidoEqualizado;
     private BigDecimal custoBrutoEqualizado;
     private BigDecimal precoMinimo;
     private BigDecimal margemMinimaLiquida;
     private BigDecimal margemMinimaBruta;
     private BigDecimal impostosSpf;
     private BigDecimal impostosSpd;
     private BigDecimal margemLiquida;
     private BigDecimal margemBruta;
     private Boolean indObrigaEqualizacao;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private BigDecimal precoLista;
     private String itDescricao;
     private BigDecimal custo;
     private BigDecimal custoEqualizado;
     private BigDecimal margemMinima;
     private BigDecimal margem;
     private BigDecimal precoRetencao;
     private String itCodigo;
     private BigDecimal qtdeEstoqueDisponivel;
     private BigDecimal qtdeEstoqueConsumida;
     private Set jrcPedidoVendaItems = new HashSet(0);

    public JrcPromocaoItemDetalhe() {
    }

	
    public JrcPromocaoItemDetalhe(JrcPromocaoItemDetalheId id, JrcEmpresa jrcEmpresa, JrcPromocaoItem jrcPromocaoItem, String flagTipoItem, BigDecimal qtde, BigDecimal precoPartida, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, BigDecimal precoLista, String itDescricao, BigDecimal precoRetencao, String itCodigo) {
        this.id = id;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcPromocaoItem = jrcPromocaoItem;
        this.flagTipoItem = flagTipoItem;
        this.qtde = qtde;
        this.precoPartida = precoPartida;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.precoLista = precoLista;
        this.itDescricao = itDescricao;
        this.precoRetencao = precoRetencao;
        this.itCodigo = itCodigo;
    }
    public JrcPromocaoItemDetalhe(JrcPromocaoItemDetalheId id, JrcEmpresa jrcEmpresa, JrcEqualizacaoItem jrcEqualizacaoItem, JrcKit jrcKit, JrcProduto jrcProduto, JrcPromocaoItem jrcPromocaoItem, JrcServicoPreco jrcServicoPreco, String flagTipoItem, Integer ctKit, BigDecimal qtde, BigDecimal precoPartida, BigDecimal custoLiquido, BigDecimal custoBruto, BigDecimal equalizacao, BigDecimal impostosEqEpd, BigDecimal impostosEqSpf, BigDecimal impostosEqSpd, BigDecimal custoLiquidoEqualizado, BigDecimal custoBrutoEqualizado, BigDecimal precoMinimo, BigDecimal margemMinimaLiquida, BigDecimal margemMinimaBruta, BigDecimal impostosSpf, BigDecimal impostosSpd, BigDecimal margemLiquida, BigDecimal margemBruta, Boolean indObrigaEqualizacao, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, BigDecimal precoLista, String itDescricao, BigDecimal custo, BigDecimal custoEqualizado, BigDecimal margemMinima, BigDecimal margem, BigDecimal precoRetencao, String itCodigo, BigDecimal qtdeEstoqueDisponivel, BigDecimal qtdeEstoqueConsumida, Set jrcPedidoVendaItems) {
       this.id = id;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcEqualizacaoItem = jrcEqualizacaoItem;
       this.jrcKit = jrcKit;
       this.jrcProduto = jrcProduto;
       this.jrcPromocaoItem = jrcPromocaoItem;
       this.jrcServicoPreco = jrcServicoPreco;
       this.flagTipoItem = flagTipoItem;
       this.ctKit = ctKit;
       this.qtde = qtde;
       this.precoPartida = precoPartida;
       this.custoLiquido = custoLiquido;
       this.custoBruto = custoBruto;
       this.equalizacao = equalizacao;
       this.impostosEqEpd = impostosEqEpd;
       this.impostosEqSpf = impostosEqSpf;
       this.impostosEqSpd = impostosEqSpd;
       this.custoLiquidoEqualizado = custoLiquidoEqualizado;
       this.custoBrutoEqualizado = custoBrutoEqualizado;
       this.precoMinimo = precoMinimo;
       this.margemMinimaLiquida = margemMinimaLiquida;
       this.margemMinimaBruta = margemMinimaBruta;
       this.impostosSpf = impostosSpf;
       this.impostosSpd = impostosSpd;
       this.margemLiquida = margemLiquida;
       this.margemBruta = margemBruta;
       this.indObrigaEqualizacao = indObrigaEqualizacao;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.precoLista = precoLista;
       this.itDescricao = itDescricao;
       this.custo = custo;
       this.custoEqualizado = custoEqualizado;
       this.margemMinima = margemMinima;
       this.margem = margem;
       this.precoRetencao = precoRetencao;
       this.itCodigo = itCodigo;
       this.qtdeEstoqueDisponivel = qtdeEstoqueDisponivel;
       this.qtdeEstoqueConsumida = qtdeEstoqueConsumida;
       this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }
   
    public JrcPromocaoItemDetalheId getId() {
        return this.id;
    }
    
    public void setId(JrcPromocaoItemDetalheId id) {
        this.id = id;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcEqualizacaoItem getJrcEqualizacaoItem() {
        return this.jrcEqualizacaoItem;
    }
    
    public void setJrcEqualizacaoItem(JrcEqualizacaoItem jrcEqualizacaoItem) {
        this.jrcEqualizacaoItem = jrcEqualizacaoItem;
    }
    public JrcKit getJrcKit() {
        return this.jrcKit;
    }
    
    public void setJrcKit(JrcKit jrcKit) {
        this.jrcKit = jrcKit;
    }
    public JrcProduto getJrcProduto() {
        return this.jrcProduto;
    }
    
    public void setJrcProduto(JrcProduto jrcProduto) {
        this.jrcProduto = jrcProduto;
    }
    public JrcPromocaoItem getJrcPromocaoItem() {
        return this.jrcPromocaoItem;
    }
    
    public void setJrcPromocaoItem(JrcPromocaoItem jrcPromocaoItem) {
        this.jrcPromocaoItem = jrcPromocaoItem;
    }
    public JrcServicoPreco getJrcServicoPreco() {
        return this.jrcServicoPreco;
    }
    
    public void setJrcServicoPreco(JrcServicoPreco jrcServicoPreco) {
        this.jrcServicoPreco = jrcServicoPreco;
    }
    public String getFlagTipoItem() {
        return this.flagTipoItem;
    }
    
    public void setFlagTipoItem(String flagTipoItem) {
        this.flagTipoItem = flagTipoItem;
    }
    public Integer getCtKit() {
        return this.ctKit;
    }
    
    public void setCtKit(Integer ctKit) {
        this.ctKit = ctKit;
    }
    public BigDecimal getQtde() {
        return this.qtde;
    }
    
    public void setQtde(BigDecimal qtde) {
        this.qtde = qtde;
    }
    public BigDecimal getPrecoPartida() {
        return this.precoPartida;
    }
    
    public void setPrecoPartida(BigDecimal precoPartida) {
        this.precoPartida = precoPartida;
    }
    public BigDecimal getCustoLiquido() {
        return this.custoLiquido;
    }
    
    public void setCustoLiquido(BigDecimal custoLiquido) {
        this.custoLiquido = custoLiquido;
    }
    public BigDecimal getCustoBruto() {
        return this.custoBruto;
    }
    
    public void setCustoBruto(BigDecimal custoBruto) {
        this.custoBruto = custoBruto;
    }
    public BigDecimal getEqualizacao() {
        return this.equalizacao;
    }
    
    public void setEqualizacao(BigDecimal equalizacao) {
        this.equalizacao = equalizacao;
    }
    public BigDecimal getImpostosEqEpd() {
        return this.impostosEqEpd;
    }
    
    public void setImpostosEqEpd(BigDecimal impostosEqEpd) {
        this.impostosEqEpd = impostosEqEpd;
    }
    public BigDecimal getImpostosEqSpf() {
        return this.impostosEqSpf;
    }
    
    public void setImpostosEqSpf(BigDecimal impostosEqSpf) {
        this.impostosEqSpf = impostosEqSpf;
    }
    public BigDecimal getImpostosEqSpd() {
        return this.impostosEqSpd;
    }
    
    public void setImpostosEqSpd(BigDecimal impostosEqSpd) {
        this.impostosEqSpd = impostosEqSpd;
    }
    public BigDecimal getCustoLiquidoEqualizado() {
        return this.custoLiquidoEqualizado;
    }
    
    public void setCustoLiquidoEqualizado(BigDecimal custoLiquidoEqualizado) {
        this.custoLiquidoEqualizado = custoLiquidoEqualizado;
    }
    public BigDecimal getCustoBrutoEqualizado() {
        return this.custoBrutoEqualizado;
    }
    
    public void setCustoBrutoEqualizado(BigDecimal custoBrutoEqualizado) {
        this.custoBrutoEqualizado = custoBrutoEqualizado;
    }
    public BigDecimal getPrecoMinimo() {
        return this.precoMinimo;
    }
    
    public void setPrecoMinimo(BigDecimal precoMinimo) {
        this.precoMinimo = precoMinimo;
    }
    public BigDecimal getMargemMinimaLiquida() {
        return this.margemMinimaLiquida;
    }
    
    public void setMargemMinimaLiquida(BigDecimal margemMinimaLiquida) {
        this.margemMinimaLiquida = margemMinimaLiquida;
    }
    public BigDecimal getMargemMinimaBruta() {
        return this.margemMinimaBruta;
    }
    
    public void setMargemMinimaBruta(BigDecimal margemMinimaBruta) {
        this.margemMinimaBruta = margemMinimaBruta;
    }
    public BigDecimal getImpostosSpf() {
        return this.impostosSpf;
    }
    
    public void setImpostosSpf(BigDecimal impostosSpf) {
        this.impostosSpf = impostosSpf;
    }
    public BigDecimal getImpostosSpd() {
        return this.impostosSpd;
    }
    
    public void setImpostosSpd(BigDecimal impostosSpd) {
        this.impostosSpd = impostosSpd;
    }
    public BigDecimal getMargemLiquida() {
        return this.margemLiquida;
    }
    
    public void setMargemLiquida(BigDecimal margemLiquida) {
        this.margemLiquida = margemLiquida;
    }
    public BigDecimal getMargemBruta() {
        return this.margemBruta;
    }
    
    public void setMargemBruta(BigDecimal margemBruta) {
        this.margemBruta = margemBruta;
    }
    public Boolean getIndObrigaEqualizacao() {
        return this.indObrigaEqualizacao;
    }
    
    public void setIndObrigaEqualizacao(Boolean indObrigaEqualizacao) {
        this.indObrigaEqualizacao = indObrigaEqualizacao;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public BigDecimal getPrecoLista() {
        return this.precoLista;
    }
    
    public void setPrecoLista(BigDecimal precoLista) {
        this.precoLista = precoLista;
    }
    public String getItDescricao() {
        return this.itDescricao;
    }
    
    public void setItDescricao(String itDescricao) {
        this.itDescricao = itDescricao;
    }
    public BigDecimal getCusto() {
        return this.custo;
    }
    
    public void setCusto(BigDecimal custo) {
        this.custo = custo;
    }
    public BigDecimal getCustoEqualizado() {
        return this.custoEqualizado;
    }
    
    public void setCustoEqualizado(BigDecimal custoEqualizado) {
        this.custoEqualizado = custoEqualizado;
    }
    public BigDecimal getMargemMinima() {
        return this.margemMinima;
    }
    
    public void setMargemMinima(BigDecimal margemMinima) {
        this.margemMinima = margemMinima;
    }
    public BigDecimal getMargem() {
        return this.margem;
    }
    
    public void setMargem(BigDecimal margem) {
        this.margem = margem;
    }
    public BigDecimal getPrecoRetencao() {
        return this.precoRetencao;
    }
    
    public void setPrecoRetencao(BigDecimal precoRetencao) {
        this.precoRetencao = precoRetencao;
    }
    public String getItCodigo() {
        return this.itCodigo;
    }
    
    public void setItCodigo(String itCodigo) {
        this.itCodigo = itCodigo;
    }
    public BigDecimal getQtdeEstoqueDisponivel() {
        return this.qtdeEstoqueDisponivel;
    }
    
    public void setQtdeEstoqueDisponivel(BigDecimal qtdeEstoqueDisponivel) {
        this.qtdeEstoqueDisponivel = qtdeEstoqueDisponivel;
    }
    public BigDecimal getQtdeEstoqueConsumida() {
        return this.qtdeEstoqueConsumida;
    }
    
    public void setQtdeEstoqueConsumida(BigDecimal qtdeEstoqueConsumida) {
        this.qtdeEstoqueConsumida = qtdeEstoqueConsumida;
    }
    public Set getJrcPedidoVendaItems() {
        return this.jrcPedidoVendaItems;
    }
    
    public void setJrcPedidoVendaItems(Set jrcPedidoVendaItems) {
        this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }




}


