package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcRotaFaturamento generated by hbm2java
 */
public class JrcRotaFaturamento  implements java.io.Serializable {


     private long idRotaFaturamento;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String descBreve;
     private String descLonga;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private boolean indEntrega;
     private boolean indMontagem;
     private boolean indOrdemServico;
     private String flagEndRota;
     private boolean indDomingo;
     private boolean indSegunda;
     private boolean indTerca;
     private boolean indQuarta;
     private boolean indQuinta;
     private boolean indSexta;
     private boolean indSabado;
     private Byte hh24Corte;
     private Set jrcNotaFiscalsForIdRotaMontagem = new HashSet(0);
     private Set jrcNotaFiscalsForIdRotaFaturamento = new HashSet(0);

    public JrcRotaFaturamento() {
    }

	
    public JrcRotaFaturamento(long idRotaFaturamento, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String descBreve, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, boolean indEntrega, boolean indMontagem, boolean indOrdemServico, String flagEndRota, boolean indDomingo, boolean indSegunda, boolean indTerca, boolean indQuarta, boolean indQuinta, boolean indSexta, boolean indSabado) {
        this.idRotaFaturamento = idRotaFaturamento;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.descBreve = descBreve;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.indEntrega = indEntrega;
        this.indMontagem = indMontagem;
        this.indOrdemServico = indOrdemServico;
        this.flagEndRota = flagEndRota;
        this.indDomingo = indDomingo;
        this.indSegunda = indSegunda;
        this.indTerca = indTerca;
        this.indQuarta = indQuarta;
        this.indQuinta = indQuinta;
        this.indSexta = indSexta;
        this.indSabado = indSabado;
    }
    public JrcRotaFaturamento(long idRotaFaturamento, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String descBreve, String descLonga, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, boolean indEntrega, boolean indMontagem, boolean indOrdemServico, String flagEndRota, boolean indDomingo, boolean indSegunda, boolean indTerca, boolean indQuarta, boolean indQuinta, boolean indSexta, boolean indSabado, Byte hh24Corte, Set jrcNotaFiscalsForIdRotaMontagem, Set jrcNotaFiscalsForIdRotaFaturamento) {
       this.idRotaFaturamento = idRotaFaturamento;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.indEntrega = indEntrega;
       this.indMontagem = indMontagem;
       this.indOrdemServico = indOrdemServico;
       this.flagEndRota = flagEndRota;
       this.indDomingo = indDomingo;
       this.indSegunda = indSegunda;
       this.indTerca = indTerca;
       this.indQuarta = indQuarta;
       this.indQuinta = indQuinta;
       this.indSexta = indSexta;
       this.indSabado = indSabado;
       this.hh24Corte = hh24Corte;
       this.jrcNotaFiscalsForIdRotaMontagem = jrcNotaFiscalsForIdRotaMontagem;
       this.jrcNotaFiscalsForIdRotaFaturamento = jrcNotaFiscalsForIdRotaFaturamento;
    }
   
    public long getIdRotaFaturamento() {
        return this.idRotaFaturamento;
    }
    
    public void setIdRotaFaturamento(long idRotaFaturamento) {
        this.idRotaFaturamento = idRotaFaturamento;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public boolean isIndEntrega() {
        return this.indEntrega;
    }
    
    public void setIndEntrega(boolean indEntrega) {
        this.indEntrega = indEntrega;
    }
    public boolean isIndMontagem() {
        return this.indMontagem;
    }
    
    public void setIndMontagem(boolean indMontagem) {
        this.indMontagem = indMontagem;
    }
    public boolean isIndOrdemServico() {
        return this.indOrdemServico;
    }
    
    public void setIndOrdemServico(boolean indOrdemServico) {
        this.indOrdemServico = indOrdemServico;
    }
    public String getFlagEndRota() {
        return this.flagEndRota;
    }
    
    public void setFlagEndRota(String flagEndRota) {
        this.flagEndRota = flagEndRota;
    }
    public boolean isIndDomingo() {
        return this.indDomingo;
    }
    
    public void setIndDomingo(boolean indDomingo) {
        this.indDomingo = indDomingo;
    }
    public boolean isIndSegunda() {
        return this.indSegunda;
    }
    
    public void setIndSegunda(boolean indSegunda) {
        this.indSegunda = indSegunda;
    }
    public boolean isIndTerca() {
        return this.indTerca;
    }
    
    public void setIndTerca(boolean indTerca) {
        this.indTerca = indTerca;
    }
    public boolean isIndQuarta() {
        return this.indQuarta;
    }
    
    public void setIndQuarta(boolean indQuarta) {
        this.indQuarta = indQuarta;
    }
    public boolean isIndQuinta() {
        return this.indQuinta;
    }
    
    public void setIndQuinta(boolean indQuinta) {
        this.indQuinta = indQuinta;
    }
    public boolean isIndSexta() {
        return this.indSexta;
    }
    
    public void setIndSexta(boolean indSexta) {
        this.indSexta = indSexta;
    }
    public boolean isIndSabado() {
        return this.indSabado;
    }
    
    public void setIndSabado(boolean indSabado) {
        this.indSabado = indSabado;
    }
    public Byte getHh24Corte() {
        return this.hh24Corte;
    }
    
    public void setHh24Corte(Byte hh24Corte) {
        this.hh24Corte = hh24Corte;
    }
    public Set getJrcNotaFiscalsForIdRotaMontagem() {
        return this.jrcNotaFiscalsForIdRotaMontagem;
    }
    
    public void setJrcNotaFiscalsForIdRotaMontagem(Set jrcNotaFiscalsForIdRotaMontagem) {
        this.jrcNotaFiscalsForIdRotaMontagem = jrcNotaFiscalsForIdRotaMontagem;
    }
    public Set getJrcNotaFiscalsForIdRotaFaturamento() {
        return this.jrcNotaFiscalsForIdRotaFaturamento;
    }
    
    public void setJrcNotaFiscalsForIdRotaFaturamento(Set jrcNotaFiscalsForIdRotaFaturamento) {
        this.jrcNotaFiscalsForIdRotaFaturamento = jrcNotaFiscalsForIdRotaFaturamento;
    }




}


