package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcSeguroCobertura generated by hbm2java
 */
public class JrcSeguroCobertura  implements java.io.Serializable {


     private long idSeguroCobertura;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String flagCobertura;
     private String descBreve;
     private String descLonga;
     private BigDecimal vrCobertura;
     private Short qtdeParcCobertura;
     private BigDecimal vrParcCobertura;
     private Short mesesCobertura;
     private BigDecimal percFranquia;
     private Short diasFranquia;
     private Short diasCarencia;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private BigDecimal percPremio;
     private Set jrcServicoPrecosForIdSeguroCoberturaRou = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaFun = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaInt = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaInv = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaQue = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaInc = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaDes = new HashSet(0);
     private Set jrcServicoPrecosForIdSeguroCoberturaMor = new HashSet(0);

    public JrcSeguroCobertura() {
    }

	
    public JrcSeguroCobertura(long idSeguroCobertura, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String flagCobertura, String descBreve, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idSeguroCobertura = idSeguroCobertura;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.flagCobertura = flagCobertura;
        this.descBreve = descBreve;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcSeguroCobertura(long idSeguroCobertura, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String flagCobertura, String descBreve, String descLonga, BigDecimal vrCobertura, Short qtdeParcCobertura, BigDecimal vrParcCobertura, Short mesesCobertura, BigDecimal percFranquia, Short diasFranquia, Short diasCarencia, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, BigDecimal percPremio, Set jrcServicoPrecosForIdSeguroCoberturaRou, Set jrcServicoPrecosForIdSeguroCoberturaFun, Set jrcServicoPrecosForIdSeguroCoberturaInt, Set jrcServicoPrecosForIdSeguroCoberturaInv, Set jrcServicoPrecosForIdSeguroCoberturaQue, Set jrcServicoPrecosForIdSeguroCoberturaInc, Set jrcServicoPrecosForIdSeguroCoberturaDes, Set jrcServicoPrecosForIdSeguroCoberturaMor) {
       this.idSeguroCobertura = idSeguroCobertura;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.flagCobertura = flagCobertura;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.vrCobertura = vrCobertura;
       this.qtdeParcCobertura = qtdeParcCobertura;
       this.vrParcCobertura = vrParcCobertura;
       this.mesesCobertura = mesesCobertura;
       this.percFranquia = percFranquia;
       this.diasFranquia = diasFranquia;
       this.diasCarencia = diasCarencia;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.percPremio = percPremio;
       this.jrcServicoPrecosForIdSeguroCoberturaRou = jrcServicoPrecosForIdSeguroCoberturaRou;
       this.jrcServicoPrecosForIdSeguroCoberturaFun = jrcServicoPrecosForIdSeguroCoberturaFun;
       this.jrcServicoPrecosForIdSeguroCoberturaInt = jrcServicoPrecosForIdSeguroCoberturaInt;
       this.jrcServicoPrecosForIdSeguroCoberturaInv = jrcServicoPrecosForIdSeguroCoberturaInv;
       this.jrcServicoPrecosForIdSeguroCoberturaQue = jrcServicoPrecosForIdSeguroCoberturaQue;
       this.jrcServicoPrecosForIdSeguroCoberturaInc = jrcServicoPrecosForIdSeguroCoberturaInc;
       this.jrcServicoPrecosForIdSeguroCoberturaDes = jrcServicoPrecosForIdSeguroCoberturaDes;
       this.jrcServicoPrecosForIdSeguroCoberturaMor = jrcServicoPrecosForIdSeguroCoberturaMor;
    }
   
    public long getIdSeguroCobertura() {
        return this.idSeguroCobertura;
    }
    
    public void setIdSeguroCobertura(long idSeguroCobertura) {
        this.idSeguroCobertura = idSeguroCobertura;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getFlagCobertura() {
        return this.flagCobertura;
    }
    
    public void setFlagCobertura(String flagCobertura) {
        this.flagCobertura = flagCobertura;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public BigDecimal getVrCobertura() {
        return this.vrCobertura;
    }
    
    public void setVrCobertura(BigDecimal vrCobertura) {
        this.vrCobertura = vrCobertura;
    }
    public Short getQtdeParcCobertura() {
        return this.qtdeParcCobertura;
    }
    
    public void setQtdeParcCobertura(Short qtdeParcCobertura) {
        this.qtdeParcCobertura = qtdeParcCobertura;
    }
    public BigDecimal getVrParcCobertura() {
        return this.vrParcCobertura;
    }
    
    public void setVrParcCobertura(BigDecimal vrParcCobertura) {
        this.vrParcCobertura = vrParcCobertura;
    }
    public Short getMesesCobertura() {
        return this.mesesCobertura;
    }
    
    public void setMesesCobertura(Short mesesCobertura) {
        this.mesesCobertura = mesesCobertura;
    }
    public BigDecimal getPercFranquia() {
        return this.percFranquia;
    }
    
    public void setPercFranquia(BigDecimal percFranquia) {
        this.percFranquia = percFranquia;
    }
    public Short getDiasFranquia() {
        return this.diasFranquia;
    }
    
    public void setDiasFranquia(Short diasFranquia) {
        this.diasFranquia = diasFranquia;
    }
    public Short getDiasCarencia() {
        return this.diasCarencia;
    }
    
    public void setDiasCarencia(Short diasCarencia) {
        this.diasCarencia = diasCarencia;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public BigDecimal getPercPremio() {
        return this.percPremio;
    }
    
    public void setPercPremio(BigDecimal percPremio) {
        this.percPremio = percPremio;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaRou() {
        return this.jrcServicoPrecosForIdSeguroCoberturaRou;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaRou(Set jrcServicoPrecosForIdSeguroCoberturaRou) {
        this.jrcServicoPrecosForIdSeguroCoberturaRou = jrcServicoPrecosForIdSeguroCoberturaRou;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaFun() {
        return this.jrcServicoPrecosForIdSeguroCoberturaFun;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaFun(Set jrcServicoPrecosForIdSeguroCoberturaFun) {
        this.jrcServicoPrecosForIdSeguroCoberturaFun = jrcServicoPrecosForIdSeguroCoberturaFun;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaInt() {
        return this.jrcServicoPrecosForIdSeguroCoberturaInt;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaInt(Set jrcServicoPrecosForIdSeguroCoberturaInt) {
        this.jrcServicoPrecosForIdSeguroCoberturaInt = jrcServicoPrecosForIdSeguroCoberturaInt;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaInv() {
        return this.jrcServicoPrecosForIdSeguroCoberturaInv;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaInv(Set jrcServicoPrecosForIdSeguroCoberturaInv) {
        this.jrcServicoPrecosForIdSeguroCoberturaInv = jrcServicoPrecosForIdSeguroCoberturaInv;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaQue() {
        return this.jrcServicoPrecosForIdSeguroCoberturaQue;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaQue(Set jrcServicoPrecosForIdSeguroCoberturaQue) {
        this.jrcServicoPrecosForIdSeguroCoberturaQue = jrcServicoPrecosForIdSeguroCoberturaQue;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaInc() {
        return this.jrcServicoPrecosForIdSeguroCoberturaInc;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaInc(Set jrcServicoPrecosForIdSeguroCoberturaInc) {
        this.jrcServicoPrecosForIdSeguroCoberturaInc = jrcServicoPrecosForIdSeguroCoberturaInc;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaDes() {
        return this.jrcServicoPrecosForIdSeguroCoberturaDes;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaDes(Set jrcServicoPrecosForIdSeguroCoberturaDes) {
        this.jrcServicoPrecosForIdSeguroCoberturaDes = jrcServicoPrecosForIdSeguroCoberturaDes;
    }
    public Set getJrcServicoPrecosForIdSeguroCoberturaMor() {
        return this.jrcServicoPrecosForIdSeguroCoberturaMor;
    }
    
    public void setJrcServicoPrecosForIdSeguroCoberturaMor(Set jrcServicoPrecosForIdSeguroCoberturaMor) {
        this.jrcServicoPrecosForIdSeguroCoberturaMor = jrcServicoPrecosForIdSeguroCoberturaMor;
    }




}


