package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcStatusProduto generated by hbm2java
 */
public class JrcStatusProduto  implements java.io.Serializable {


     private long idStatusProduto;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String sigla;
     private String descBreve;
     private String descLonga;
     private String flagStatus;
     private boolean indPermiteCompra;
     private boolean indPermiteVenda;
     private Short diasReposicao;
     private Date dtInicioPeriodo;
     private Date dtFimPeriodo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String flagVendaSe;
     private Boolean indLiberacaoVendaSe;
     private String flagCor;
     private Boolean indPadraoRelcom;
     private Set jrcKits = new HashSet(0);
     private Set jrcProdutos = new HashSet(0);
     private Set jrcPedidoVendaItems = new HashSet(0);

    public JrcStatusProduto() {
    }

	
    public JrcStatusProduto(long idStatusProduto, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String sigla, String descBreve, String flagStatus, boolean indPermiteCompra, boolean indPermiteVenda, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idStatusProduto = idStatusProduto;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.sigla = sigla;
        this.descBreve = descBreve;
        this.flagStatus = flagStatus;
        this.indPermiteCompra = indPermiteCompra;
        this.indPermiteVenda = indPermiteVenda;
        this.dtInicioPeriodo = dtInicioPeriodo;
        this.dtFimPeriodo = dtFimPeriodo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcStatusProduto(long idStatusProduto, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String sigla, String descBreve, String descLonga, String flagStatus, boolean indPermiteCompra, boolean indPermiteVenda, Short diasReposicao, Date dtInicioPeriodo, Date dtFimPeriodo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String flagVendaSe, Boolean indLiberacaoVendaSe, String flagCor, Boolean indPadraoRelcom, Set jrcKits, Set jrcProdutos, Set jrcPedidoVendaItems) {
       this.idStatusProduto = idStatusProduto;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.sigla = sigla;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.flagStatus = flagStatus;
       this.indPermiteCompra = indPermiteCompra;
       this.indPermiteVenda = indPermiteVenda;
       this.diasReposicao = diasReposicao;
       this.dtInicioPeriodo = dtInicioPeriodo;
       this.dtFimPeriodo = dtFimPeriodo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.flagVendaSe = flagVendaSe;
       this.indLiberacaoVendaSe = indLiberacaoVendaSe;
       this.flagCor = flagCor;
       this.indPadraoRelcom = indPadraoRelcom;
       this.jrcKits = jrcKits;
       this.jrcProdutos = jrcProdutos;
       this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }
   
    public long getIdStatusProduto() {
        return this.idStatusProduto;
    }
    
    public void setIdStatusProduto(long idStatusProduto) {
        this.idStatusProduto = idStatusProduto;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public String getFlagStatus() {
        return this.flagStatus;
    }
    
    public void setFlagStatus(String flagStatus) {
        this.flagStatus = flagStatus;
    }
    public boolean isIndPermiteCompra() {
        return this.indPermiteCompra;
    }
    
    public void setIndPermiteCompra(boolean indPermiteCompra) {
        this.indPermiteCompra = indPermiteCompra;
    }
    public boolean isIndPermiteVenda() {
        return this.indPermiteVenda;
    }
    
    public void setIndPermiteVenda(boolean indPermiteVenda) {
        this.indPermiteVenda = indPermiteVenda;
    }
    public Short getDiasReposicao() {
        return this.diasReposicao;
    }
    
    public void setDiasReposicao(Short diasReposicao) {
        this.diasReposicao = diasReposicao;
    }
    public Date getDtInicioPeriodo() {
        return this.dtInicioPeriodo;
    }
    
    public void setDtInicioPeriodo(Date dtInicioPeriodo) {
        this.dtInicioPeriodo = dtInicioPeriodo;
    }
    public Date getDtFimPeriodo() {
        return this.dtFimPeriodo;
    }
    
    public void setDtFimPeriodo(Date dtFimPeriodo) {
        this.dtFimPeriodo = dtFimPeriodo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getFlagVendaSe() {
        return this.flagVendaSe;
    }
    
    public void setFlagVendaSe(String flagVendaSe) {
        this.flagVendaSe = flagVendaSe;
    }
    public Boolean getIndLiberacaoVendaSe() {
        return this.indLiberacaoVendaSe;
    }
    
    public void setIndLiberacaoVendaSe(Boolean indLiberacaoVendaSe) {
        this.indLiberacaoVendaSe = indLiberacaoVendaSe;
    }
    public String getFlagCor() {
        return this.flagCor;
    }
    
    public void setFlagCor(String flagCor) {
        this.flagCor = flagCor;
    }
    public Boolean getIndPadraoRelcom() {
        return this.indPadraoRelcom;
    }
    
    public void setIndPadraoRelcom(Boolean indPadraoRelcom) {
        this.indPadraoRelcom = indPadraoRelcom;
    }
    public Set getJrcKits() {
        return this.jrcKits;
    }
    
    public void setJrcKits(Set jrcKits) {
        this.jrcKits = jrcKits;
    }
    public Set getJrcProdutos() {
        return this.jrcProdutos;
    }
    
    public void setJrcProdutos(Set jrcProdutos) {
        this.jrcProdutos = jrcProdutos;
    }
    public Set getJrcPedidoVendaItems() {
        return this.jrcPedidoVendaItems;
    }
    
    public void setJrcPedidoVendaItems(Set jrcPedidoVendaItems) {
        this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }




}


