package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcTesouraria generated by hbm2java
 */
public class JrcTesouraria  implements java.io.Serializable {


     private long idTesouraria;
     private JrcEmpresa jrcEmpresa;
     private JrcLoja jrcLoja;
     private JrcTesouraria jrcTesouraria;
     private JrcUsuario jrcUsuario;
     private Byte limiteDiasFech;
     private Byte limiteDiasConf;
     private boolean indAtivo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private boolean indExigeCancPedido;
     private BigDecimal saldoDinMax;
     private Short maxDiasCheAgDep;
     private Boolean indBorderoTransferencia;
     private Boolean indBorderoSaida;
     private Boolean indBorderoEntrada;
     private Boolean indBorderoDepositoDin;
     private Boolean indBorderoDepositoChe;
     private Byte diasCancPedidoCre;
     private Set jrcPdvs = new HashSet(0);
     private Set jrcProcessoPdvs = new HashSet(0);
     private Set jrcTesourarias = new HashSet(0);
     private Set jrcMovimentoTesourarias = new HashSet(0);

    public JrcTesouraria() {
    }

	
    public JrcTesouraria(long idTesouraria, JrcEmpresa jrcEmpresa, JrcLoja jrcLoja, JrcUsuario jrcUsuario, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, boolean indExigeCancPedido) {
        this.idTesouraria = idTesouraria;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcLoja = jrcLoja;
        this.jrcUsuario = jrcUsuario;
        this.indAtivo = indAtivo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
        this.indExigeCancPedido = indExigeCancPedido;
    }
    public JrcTesouraria(long idTesouraria, JrcEmpresa jrcEmpresa, JrcLoja jrcLoja, JrcTesouraria jrcTesouraria, JrcUsuario jrcUsuario, Byte limiteDiasFech, Byte limiteDiasConf, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, boolean indExigeCancPedido, BigDecimal saldoDinMax, Short maxDiasCheAgDep, Boolean indBorderoTransferencia, Boolean indBorderoSaida, Boolean indBorderoEntrada, Boolean indBorderoDepositoDin, Boolean indBorderoDepositoChe, Byte diasCancPedidoCre, Set jrcPdvs, Set jrcProcessoPdvs, Set jrcTesourarias, Set jrcMovimentoTesourarias) {
       this.idTesouraria = idTesouraria;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcLoja = jrcLoja;
       this.jrcTesouraria = jrcTesouraria;
       this.jrcUsuario = jrcUsuario;
       this.limiteDiasFech = limiteDiasFech;
       this.limiteDiasConf = limiteDiasConf;
       this.indAtivo = indAtivo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.indExigeCancPedido = indExigeCancPedido;
       this.saldoDinMax = saldoDinMax;
       this.maxDiasCheAgDep = maxDiasCheAgDep;
       this.indBorderoTransferencia = indBorderoTransferencia;
       this.indBorderoSaida = indBorderoSaida;
       this.indBorderoEntrada = indBorderoEntrada;
       this.indBorderoDepositoDin = indBorderoDepositoDin;
       this.indBorderoDepositoChe = indBorderoDepositoChe;
       this.diasCancPedidoCre = diasCancPedidoCre;
       this.jrcPdvs = jrcPdvs;
       this.jrcProcessoPdvs = jrcProcessoPdvs;
       this.jrcTesourarias = jrcTesourarias;
       this.jrcMovimentoTesourarias = jrcMovimentoTesourarias;
    }
   
    public long getIdTesouraria() {
        return this.idTesouraria;
    }
    
    public void setIdTesouraria(long idTesouraria) {
        this.idTesouraria = idTesouraria;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcLoja getJrcLoja() {
        return this.jrcLoja;
    }
    
    public void setJrcLoja(JrcLoja jrcLoja) {
        this.jrcLoja = jrcLoja;
    }
    public JrcTesouraria getJrcTesouraria() {
        return this.jrcTesouraria;
    }
    
    public void setJrcTesouraria(JrcTesouraria jrcTesouraria) {
        this.jrcTesouraria = jrcTesouraria;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public Byte getLimiteDiasFech() {
        return this.limiteDiasFech;
    }
    
    public void setLimiteDiasFech(Byte limiteDiasFech) {
        this.limiteDiasFech = limiteDiasFech;
    }
    public Byte getLimiteDiasConf() {
        return this.limiteDiasConf;
    }
    
    public void setLimiteDiasConf(Byte limiteDiasConf) {
        this.limiteDiasConf = limiteDiasConf;
    }
    public boolean isIndAtivo() {
        return this.indAtivo;
    }
    
    public void setIndAtivo(boolean indAtivo) {
        this.indAtivo = indAtivo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public boolean isIndExigeCancPedido() {
        return this.indExigeCancPedido;
    }
    
    public void setIndExigeCancPedido(boolean indExigeCancPedido) {
        this.indExigeCancPedido = indExigeCancPedido;
    }
    public BigDecimal getSaldoDinMax() {
        return this.saldoDinMax;
    }
    
    public void setSaldoDinMax(BigDecimal saldoDinMax) {
        this.saldoDinMax = saldoDinMax;
    }
    public Short getMaxDiasCheAgDep() {
        return this.maxDiasCheAgDep;
    }
    
    public void setMaxDiasCheAgDep(Short maxDiasCheAgDep) {
        this.maxDiasCheAgDep = maxDiasCheAgDep;
    }
    public Boolean getIndBorderoTransferencia() {
        return this.indBorderoTransferencia;
    }
    
    public void setIndBorderoTransferencia(Boolean indBorderoTransferencia) {
        this.indBorderoTransferencia = indBorderoTransferencia;
    }
    public Boolean getIndBorderoSaida() {
        return this.indBorderoSaida;
    }
    
    public void setIndBorderoSaida(Boolean indBorderoSaida) {
        this.indBorderoSaida = indBorderoSaida;
    }
    public Boolean getIndBorderoEntrada() {
        return this.indBorderoEntrada;
    }
    
    public void setIndBorderoEntrada(Boolean indBorderoEntrada) {
        this.indBorderoEntrada = indBorderoEntrada;
    }
    public Boolean getIndBorderoDepositoDin() {
        return this.indBorderoDepositoDin;
    }
    
    public void setIndBorderoDepositoDin(Boolean indBorderoDepositoDin) {
        this.indBorderoDepositoDin = indBorderoDepositoDin;
    }
    public Boolean getIndBorderoDepositoChe() {
        return this.indBorderoDepositoChe;
    }
    
    public void setIndBorderoDepositoChe(Boolean indBorderoDepositoChe) {
        this.indBorderoDepositoChe = indBorderoDepositoChe;
    }
    public Byte getDiasCancPedidoCre() {
        return this.diasCancPedidoCre;
    }
    
    public void setDiasCancPedidoCre(Byte diasCancPedidoCre) {
        this.diasCancPedidoCre = diasCancPedidoCre;
    }
    public Set getJrcPdvs() {
        return this.jrcPdvs;
    }
    
    public void setJrcPdvs(Set jrcPdvs) {
        this.jrcPdvs = jrcPdvs;
    }
    public Set getJrcProcessoPdvs() {
        return this.jrcProcessoPdvs;
    }
    
    public void setJrcProcessoPdvs(Set jrcProcessoPdvs) {
        this.jrcProcessoPdvs = jrcProcessoPdvs;
    }
    public Set getJrcTesourarias() {
        return this.jrcTesourarias;
    }
    
    public void setJrcTesourarias(Set jrcTesourarias) {
        this.jrcTesourarias = jrcTesourarias;
    }
    public Set getJrcMovimentoTesourarias() {
        return this.jrcMovimentoTesourarias;
    }
    
    public void setJrcMovimentoTesourarias(Set jrcMovimentoTesourarias) {
        this.jrcMovimentoTesourarias = jrcMovimentoTesourarias;
    }




}


