package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcTransacaoTef generated by hbm2java
 */
public class JrcTransacaoTef  implements java.io.Serializable {


     private long idTransacaoTef;
     private JrcEmpresa jrcEmpresa;
     private JrcOperacaoTef jrcOperacaoTef;
     private JrcTef jrcTef;
     private String flagTef;
     private String flagOperacaoTef;
     private String flagComportamentoTef;
     private Date dtTransacao;
     private String operador;
     private BigDecimal vrPagto;
     private String flagTipoPagtoTef;
     private Short plano;
     private Boolean indVenctoAniversario;
     private Short venctoIntervalo;
     private Date dtPredatado;
     private Boolean indCarDigitado;
     private String carNumero;
     private Byte carMesValidade;
     private Short carAnoValidade;
     private String carCodigoSeguranca;
     private Boolean indChequeDigitado;
     private String cheCmc7;
     private Boolean cheIndPessoaFisica;
     private Long cheCpfCnpj;
     private Boolean indAutorizada;
     private String redeAutorizadora;
     private String bandeira;
     private String bin;
     private String meioPagamento;
     private String nsuTef;
     private Date dtTef;
     private String nsuAutorizadora;
     private String codigoAutorizadora;
     private String instituicao;
     private String estabelecimento;
     private String flagStatus;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private BigDecimal vrSaque;
     private String idTransacao;
     private Boolean indPermiteCartaoDigitado;
     private String observacao;
     private Boolean indPlanoComEntrada;
     private Date dtTefOriginal;
     private String nsuTefOriginal;
     private Clob comprovante;
     private long versaoRegistro;
     private String descricaoBandeira;
     private Long auto;
     private String operadora;
     private String ddd;
     private String telefone;
     private String nsuTefRecarga;
     private Date dtTefRecarga;
     private String nsuAutorizadoraRecarga;
     private Set jrcPedidoVendaItems = new HashSet(0);

    public JrcTransacaoTef() {
    }

	
    public JrcTransacaoTef(long idTransacaoTef, JrcEmpresa jrcEmpresa, JrcOperacaoTef jrcOperacaoTef, JrcTef jrcTef, String flagTef, String flagOperacaoTef, String flagComportamentoTef, String flagStatus, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idTransacaoTef = idTransacaoTef;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcOperacaoTef = jrcOperacaoTef;
        this.jrcTef = jrcTef;
        this.flagTef = flagTef;
        this.flagOperacaoTef = flagOperacaoTef;
        this.flagComportamentoTef = flagComportamentoTef;
        this.flagStatus = flagStatus;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcTransacaoTef(long idTransacaoTef, JrcEmpresa jrcEmpresa, JrcOperacaoTef jrcOperacaoTef, JrcTef jrcTef, String flagTef, String flagOperacaoTef, String flagComportamentoTef, Date dtTransacao, String operador, BigDecimal vrPagto, String flagTipoPagtoTef, Short plano, Boolean indVenctoAniversario, Short venctoIntervalo, Date dtPredatado, Boolean indCarDigitado, String carNumero, Byte carMesValidade, Short carAnoValidade, String carCodigoSeguranca, Boolean indChequeDigitado, String cheCmc7, Boolean cheIndPessoaFisica, Long cheCpfCnpj, Boolean indAutorizada, String redeAutorizadora, String bandeira, String bin, String meioPagamento, String nsuTef, Date dtTef, String nsuAutorizadora, String codigoAutorizadora, String instituicao, String estabelecimento, String flagStatus, Date dtInclusao, Date dtAlteracao, long versaoSistema, BigDecimal vrSaque, String idTransacao, Boolean indPermiteCartaoDigitado, String observacao, Boolean indPlanoComEntrada, Date dtTefOriginal, String nsuTefOriginal, Clob comprovante, long versaoRegistro, String descricaoBandeira, Long auto, String operadora, String ddd, String telefone, String nsuTefRecarga, Date dtTefRecarga, String nsuAutorizadoraRecarga, Set jrcPedidoVendaItems) {
       this.idTransacaoTef = idTransacaoTef;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcOperacaoTef = jrcOperacaoTef;
       this.jrcTef = jrcTef;
       this.flagTef = flagTef;
       this.flagOperacaoTef = flagOperacaoTef;
       this.flagComportamentoTef = flagComportamentoTef;
       this.dtTransacao = dtTransacao;
       this.operador = operador;
       this.vrPagto = vrPagto;
       this.flagTipoPagtoTef = flagTipoPagtoTef;
       this.plano = plano;
       this.indVenctoAniversario = indVenctoAniversario;
       this.venctoIntervalo = venctoIntervalo;
       this.dtPredatado = dtPredatado;
       this.indCarDigitado = indCarDigitado;
       this.carNumero = carNumero;
       this.carMesValidade = carMesValidade;
       this.carAnoValidade = carAnoValidade;
       this.carCodigoSeguranca = carCodigoSeguranca;
       this.indChequeDigitado = indChequeDigitado;
       this.cheCmc7 = cheCmc7;
       this.cheIndPessoaFisica = cheIndPessoaFisica;
       this.cheCpfCnpj = cheCpfCnpj;
       this.indAutorizada = indAutorizada;
       this.redeAutorizadora = redeAutorizadora;
       this.bandeira = bandeira;
       this.bin = bin;
       this.meioPagamento = meioPagamento;
       this.nsuTef = nsuTef;
       this.dtTef = dtTef;
       this.nsuAutorizadora = nsuAutorizadora;
       this.codigoAutorizadora = codigoAutorizadora;
       this.instituicao = instituicao;
       this.estabelecimento = estabelecimento;
       this.flagStatus = flagStatus;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.vrSaque = vrSaque;
       this.idTransacao = idTransacao;
       this.indPermiteCartaoDigitado = indPermiteCartaoDigitado;
       this.observacao = observacao;
       this.indPlanoComEntrada = indPlanoComEntrada;
       this.dtTefOriginal = dtTefOriginal;
       this.nsuTefOriginal = nsuTefOriginal;
       this.comprovante = comprovante;
       this.versaoRegistro = versaoRegistro;
       this.descricaoBandeira = descricaoBandeira;
       this.auto = auto;
       this.operadora = operadora;
       this.ddd = ddd;
       this.telefone = telefone;
       this.nsuTefRecarga = nsuTefRecarga;
       this.dtTefRecarga = dtTefRecarga;
       this.nsuAutorizadoraRecarga = nsuAutorizadoraRecarga;
       this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }
   
    public long getIdTransacaoTef() {
        return this.idTransacaoTef;
    }
    
    public void setIdTransacaoTef(long idTransacaoTef) {
        this.idTransacaoTef = idTransacaoTef;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcOperacaoTef getJrcOperacaoTef() {
        return this.jrcOperacaoTef;
    }
    
    public void setJrcOperacaoTef(JrcOperacaoTef jrcOperacaoTef) {
        this.jrcOperacaoTef = jrcOperacaoTef;
    }
    public JrcTef getJrcTef() {
        return this.jrcTef;
    }
    
    public void setJrcTef(JrcTef jrcTef) {
        this.jrcTef = jrcTef;
    }
    public String getFlagTef() {
        return this.flagTef;
    }
    
    public void setFlagTef(String flagTef) {
        this.flagTef = flagTef;
    }
    public String getFlagOperacaoTef() {
        return this.flagOperacaoTef;
    }
    
    public void setFlagOperacaoTef(String flagOperacaoTef) {
        this.flagOperacaoTef = flagOperacaoTef;
    }
    public String getFlagComportamentoTef() {
        return this.flagComportamentoTef;
    }
    
    public void setFlagComportamentoTef(String flagComportamentoTef) {
        this.flagComportamentoTef = flagComportamentoTef;
    }
    public Date getDtTransacao() {
        return this.dtTransacao;
    }
    
    public void setDtTransacao(Date dtTransacao) {
        this.dtTransacao = dtTransacao;
    }
    public String getOperador() {
        return this.operador;
    }
    
    public void setOperador(String operador) {
        this.operador = operador;
    }
    public BigDecimal getVrPagto() {
        return this.vrPagto;
    }
    
    public void setVrPagto(BigDecimal vrPagto) {
        this.vrPagto = vrPagto;
    }
    public String getFlagTipoPagtoTef() {
        return this.flagTipoPagtoTef;
    }
    
    public void setFlagTipoPagtoTef(String flagTipoPagtoTef) {
        this.flagTipoPagtoTef = flagTipoPagtoTef;
    }
    public Short getPlano() {
        return this.plano;
    }
    
    public void setPlano(Short plano) {
        this.plano = plano;
    }
    public Boolean getIndVenctoAniversario() {
        return this.indVenctoAniversario;
    }
    
    public void setIndVenctoAniversario(Boolean indVenctoAniversario) {
        this.indVenctoAniversario = indVenctoAniversario;
    }
    public Short getVenctoIntervalo() {
        return this.venctoIntervalo;
    }
    
    public void setVenctoIntervalo(Short venctoIntervalo) {
        this.venctoIntervalo = venctoIntervalo;
    }
    public Date getDtPredatado() {
        return this.dtPredatado;
    }
    
    public void setDtPredatado(Date dtPredatado) {
        this.dtPredatado = dtPredatado;
    }
    public Boolean getIndCarDigitado() {
        return this.indCarDigitado;
    }
    
    public void setIndCarDigitado(Boolean indCarDigitado) {
        this.indCarDigitado = indCarDigitado;
    }
    public String getCarNumero() {
        return this.carNumero;
    }
    
    public void setCarNumero(String carNumero) {
        this.carNumero = carNumero;
    }
    public Byte getCarMesValidade() {
        return this.carMesValidade;
    }
    
    public void setCarMesValidade(Byte carMesValidade) {
        this.carMesValidade = carMesValidade;
    }
    public Short getCarAnoValidade() {
        return this.carAnoValidade;
    }
    
    public void setCarAnoValidade(Short carAnoValidade) {
        this.carAnoValidade = carAnoValidade;
    }
    public String getCarCodigoSeguranca() {
        return this.carCodigoSeguranca;
    }
    
    public void setCarCodigoSeguranca(String carCodigoSeguranca) {
        this.carCodigoSeguranca = carCodigoSeguranca;
    }
    public Boolean getIndChequeDigitado() {
        return this.indChequeDigitado;
    }
    
    public void setIndChequeDigitado(Boolean indChequeDigitado) {
        this.indChequeDigitado = indChequeDigitado;
    }
    public String getCheCmc7() {
        return this.cheCmc7;
    }
    
    public void setCheCmc7(String cheCmc7) {
        this.cheCmc7 = cheCmc7;
    }
    public Boolean getCheIndPessoaFisica() {
        return this.cheIndPessoaFisica;
    }
    
    public void setCheIndPessoaFisica(Boolean cheIndPessoaFisica) {
        this.cheIndPessoaFisica = cheIndPessoaFisica;
    }
    public Long getCheCpfCnpj() {
        return this.cheCpfCnpj;
    }
    
    public void setCheCpfCnpj(Long cheCpfCnpj) {
        this.cheCpfCnpj = cheCpfCnpj;
    }
    public Boolean getIndAutorizada() {
        return this.indAutorizada;
    }
    
    public void setIndAutorizada(Boolean indAutorizada) {
        this.indAutorizada = indAutorizada;
    }
    public String getRedeAutorizadora() {
        return this.redeAutorizadora;
    }
    
    public void setRedeAutorizadora(String redeAutorizadora) {
        this.redeAutorizadora = redeAutorizadora;
    }
    public String getBandeira() {
        return this.bandeira;
    }
    
    public void setBandeira(String bandeira) {
        this.bandeira = bandeira;
    }
    public String getBin() {
        return this.bin;
    }
    
    public void setBin(String bin) {
        this.bin = bin;
    }
    public String getMeioPagamento() {
        return this.meioPagamento;
    }
    
    public void setMeioPagamento(String meioPagamento) {
        this.meioPagamento = meioPagamento;
    }
    public String getNsuTef() {
        return this.nsuTef;
    }
    
    public void setNsuTef(String nsuTef) {
        this.nsuTef = nsuTef;
    }
    public Date getDtTef() {
        return this.dtTef;
    }
    
    public void setDtTef(Date dtTef) {
        this.dtTef = dtTef;
    }
    public String getNsuAutorizadora() {
        return this.nsuAutorizadora;
    }
    
    public void setNsuAutorizadora(String nsuAutorizadora) {
        this.nsuAutorizadora = nsuAutorizadora;
    }
    public String getCodigoAutorizadora() {
        return this.codigoAutorizadora;
    }
    
    public void setCodigoAutorizadora(String codigoAutorizadora) {
        this.codigoAutorizadora = codigoAutorizadora;
    }
    public String getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }
    public String getEstabelecimento() {
        return this.estabelecimento;
    }
    
    public void setEstabelecimento(String estabelecimento) {
        this.estabelecimento = estabelecimento;
    }
    public String getFlagStatus() {
        return this.flagStatus;
    }
    
    public void setFlagStatus(String flagStatus) {
        this.flagStatus = flagStatus;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public BigDecimal getVrSaque() {
        return this.vrSaque;
    }
    
    public void setVrSaque(BigDecimal vrSaque) {
        this.vrSaque = vrSaque;
    }
    public String getIdTransacao() {
        return this.idTransacao;
    }
    
    public void setIdTransacao(String idTransacao) {
        this.idTransacao = idTransacao;
    }
    public Boolean getIndPermiteCartaoDigitado() {
        return this.indPermiteCartaoDigitado;
    }
    
    public void setIndPermiteCartaoDigitado(Boolean indPermiteCartaoDigitado) {
        this.indPermiteCartaoDigitado = indPermiteCartaoDigitado;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Boolean getIndPlanoComEntrada() {
        return this.indPlanoComEntrada;
    }
    
    public void setIndPlanoComEntrada(Boolean indPlanoComEntrada) {
        this.indPlanoComEntrada = indPlanoComEntrada;
    }
    public Date getDtTefOriginal() {
        return this.dtTefOriginal;
    }
    
    public void setDtTefOriginal(Date dtTefOriginal) {
        this.dtTefOriginal = dtTefOriginal;
    }
    public String getNsuTefOriginal() {
        return this.nsuTefOriginal;
    }
    
    public void setNsuTefOriginal(String nsuTefOriginal) {
        this.nsuTefOriginal = nsuTefOriginal;
    }
    public Clob getComprovante() {
        return this.comprovante;
    }
    
    public void setComprovante(Clob comprovante) {
        this.comprovante = comprovante;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getDescricaoBandeira() {
        return this.descricaoBandeira;
    }
    
    public void setDescricaoBandeira(String descricaoBandeira) {
        this.descricaoBandeira = descricaoBandeira;
    }
    public Long getAuto() {
        return this.auto;
    }
    
    public void setAuto(Long auto) {
        this.auto = auto;
    }
    public String getOperadora() {
        return this.operadora;
    }
    
    public void setOperadora(String operadora) {
        this.operadora = operadora;
    }
    public String getDdd() {
        return this.ddd;
    }
    
    public void setDdd(String ddd) {
        this.ddd = ddd;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getNsuTefRecarga() {
        return this.nsuTefRecarga;
    }
    
    public void setNsuTefRecarga(String nsuTefRecarga) {
        this.nsuTefRecarga = nsuTefRecarga;
    }
    public Date getDtTefRecarga() {
        return this.dtTefRecarga;
    }
    
    public void setDtTefRecarga(Date dtTefRecarga) {
        this.dtTefRecarga = dtTefRecarga;
    }
    public String getNsuAutorizadoraRecarga() {
        return this.nsuAutorizadoraRecarga;
    }
    
    public void setNsuAutorizadoraRecarga(String nsuAutorizadoraRecarga) {
        this.nsuAutorizadoraRecarga = nsuAutorizadoraRecarga;
    }
    public Set getJrcPedidoVendaItems() {
        return this.jrcPedidoVendaItems;
    }
    
    public void setJrcPedidoVendaItems(Set jrcPedidoVendaItems) {
        this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }




}


