package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcTipoCliente generated by hbm2java
 */
public class JrcTipoCliente  implements java.io.Serializable {


     private long idTipoCliente;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String descBreve;
     private String descLonga;
     private boolean indAtivo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String sigla;
     private Short qtdeTotContratoDe;
     private Short qtdeTotContratoAte;
     private Short diasAtrasoAtualDe;
     private Short diasAtrasoAtualAte;
     private BigDecimal vrAtrasoAtualDe;
     private BigDecimal vrAtrasoAtualAte;
     private BigDecimal percAtrasoAtualDe;
     private BigDecimal percAtrasoAtualAte;
     private Set jrcPedidoVendas = new HashSet(0);

    public JrcTipoCliente() {
    }

	
    public JrcTipoCliente(long idTipoCliente, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String descBreve, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idTipoCliente = idTipoCliente;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.descBreve = descBreve;
        this.indAtivo = indAtivo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcTipoCliente(long idTipoCliente, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String descBreve, String descLonga, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String sigla, Short qtdeTotContratoDe, Short qtdeTotContratoAte, Short diasAtrasoAtualDe, Short diasAtrasoAtualAte, BigDecimal vrAtrasoAtualDe, BigDecimal vrAtrasoAtualAte, BigDecimal percAtrasoAtualDe, BigDecimal percAtrasoAtualAte, Set jrcPedidoVendas) {
       this.idTipoCliente = idTipoCliente;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.indAtivo = indAtivo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.sigla = sigla;
       this.qtdeTotContratoDe = qtdeTotContratoDe;
       this.qtdeTotContratoAte = qtdeTotContratoAte;
       this.diasAtrasoAtualDe = diasAtrasoAtualDe;
       this.diasAtrasoAtualAte = diasAtrasoAtualAte;
       this.vrAtrasoAtualDe = vrAtrasoAtualDe;
       this.vrAtrasoAtualAte = vrAtrasoAtualAte;
       this.percAtrasoAtualDe = percAtrasoAtualDe;
       this.percAtrasoAtualAte = percAtrasoAtualAte;
       this.jrcPedidoVendas = jrcPedidoVendas;
    }
   
    public long getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(long idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public boolean isIndAtivo() {
        return this.indAtivo;
    }
    
    public void setIndAtivo(boolean indAtivo) {
        this.indAtivo = indAtivo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Short getQtdeTotContratoDe() {
        return this.qtdeTotContratoDe;
    }
    
    public void setQtdeTotContratoDe(Short qtdeTotContratoDe) {
        this.qtdeTotContratoDe = qtdeTotContratoDe;
    }
    public Short getQtdeTotContratoAte() {
        return this.qtdeTotContratoAte;
    }
    
    public void setQtdeTotContratoAte(Short qtdeTotContratoAte) {
        this.qtdeTotContratoAte = qtdeTotContratoAte;
    }
    public Short getDiasAtrasoAtualDe() {
        return this.diasAtrasoAtualDe;
    }
    
    public void setDiasAtrasoAtualDe(Short diasAtrasoAtualDe) {
        this.diasAtrasoAtualDe = diasAtrasoAtualDe;
    }
    public Short getDiasAtrasoAtualAte() {
        return this.diasAtrasoAtualAte;
    }
    
    public void setDiasAtrasoAtualAte(Short diasAtrasoAtualAte) {
        this.diasAtrasoAtualAte = diasAtrasoAtualAte;
    }
    public BigDecimal getVrAtrasoAtualDe() {
        return this.vrAtrasoAtualDe;
    }
    
    public void setVrAtrasoAtualDe(BigDecimal vrAtrasoAtualDe) {
        this.vrAtrasoAtualDe = vrAtrasoAtualDe;
    }
    public BigDecimal getVrAtrasoAtualAte() {
        return this.vrAtrasoAtualAte;
    }
    
    public void setVrAtrasoAtualAte(BigDecimal vrAtrasoAtualAte) {
        this.vrAtrasoAtualAte = vrAtrasoAtualAte;
    }
    public BigDecimal getPercAtrasoAtualDe() {
        return this.percAtrasoAtualDe;
    }
    
    public void setPercAtrasoAtualDe(BigDecimal percAtrasoAtualDe) {
        this.percAtrasoAtualDe = percAtrasoAtualDe;
    }
    public BigDecimal getPercAtrasoAtualAte() {
        return this.percAtrasoAtualAte;
    }
    
    public void setPercAtrasoAtualAte(BigDecimal percAtrasoAtualAte) {
        this.percAtrasoAtualAte = percAtrasoAtualAte;
    }
    public Set getJrcPedidoVendas() {
        return this.jrcPedidoVendas;
    }
    
    public void setJrcPedidoVendas(Set jrcPedidoVendas) {
        this.jrcPedidoVendas = jrcPedidoVendas;
    }




}


