package br.com.gr.pojo;
// Generated 19/02/2017 12:53:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JrcUnidade generated by hbm2java
 */
public class JrcUnidade  implements java.io.Serializable {


     private long idUnidade;
     private JrcEmpresa jrcEmpresa;
     private JrcUsuario jrcUsuario;
     private String sigla;
     private String descBreve;
     private String descLonga;
     private boolean indFracionada;
     private String flagTipo;
     private boolean indAtivo;
     private Date dtInclusao;
     private Date dtAlteracao;
     private long versaoSistema;
     private long versaoRegistro;
     private String hash1;
     private Set jrcKits = new HashSet(0);
     private Set jrcProdutos = new HashSet(0);
     private Set jrcServicos = new HashSet(0);
     private Set jrcPedidoVendaItems = new HashSet(0);

    public JrcUnidade() {
    }

	
    public JrcUnidade(long idUnidade, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String sigla, String descBreve, boolean indFracionada, String flagTipo, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro) {
        this.idUnidade = idUnidade;
        this.jrcEmpresa = jrcEmpresa;
        this.jrcUsuario = jrcUsuario;
        this.sigla = sigla;
        this.descBreve = descBreve;
        this.indFracionada = indFracionada;
        this.flagTipo = flagTipo;
        this.indAtivo = indAtivo;
        this.dtInclusao = dtInclusao;
        this.dtAlteracao = dtAlteracao;
        this.versaoSistema = versaoSistema;
        this.versaoRegistro = versaoRegistro;
    }
    public JrcUnidade(long idUnidade, JrcEmpresa jrcEmpresa, JrcUsuario jrcUsuario, String sigla, String descBreve, String descLonga, boolean indFracionada, String flagTipo, boolean indAtivo, Date dtInclusao, Date dtAlteracao, long versaoSistema, long versaoRegistro, String hash1, Set jrcKits, Set jrcProdutos, Set jrcServicos, Set jrcPedidoVendaItems) {
       this.idUnidade = idUnidade;
       this.jrcEmpresa = jrcEmpresa;
       this.jrcUsuario = jrcUsuario;
       this.sigla = sigla;
       this.descBreve = descBreve;
       this.descLonga = descLonga;
       this.indFracionada = indFracionada;
       this.flagTipo = flagTipo;
       this.indAtivo = indAtivo;
       this.dtInclusao = dtInclusao;
       this.dtAlteracao = dtAlteracao;
       this.versaoSistema = versaoSistema;
       this.versaoRegistro = versaoRegistro;
       this.hash1 = hash1;
       this.jrcKits = jrcKits;
       this.jrcProdutos = jrcProdutos;
       this.jrcServicos = jrcServicos;
       this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }
   
    public long getIdUnidade() {
        return this.idUnidade;
    }
    
    public void setIdUnidade(long idUnidade) {
        this.idUnidade = idUnidade;
    }
    public JrcEmpresa getJrcEmpresa() {
        return this.jrcEmpresa;
    }
    
    public void setJrcEmpresa(JrcEmpresa jrcEmpresa) {
        this.jrcEmpresa = jrcEmpresa;
    }
    public JrcUsuario getJrcUsuario() {
        return this.jrcUsuario;
    }
    
    public void setJrcUsuario(JrcUsuario jrcUsuario) {
        this.jrcUsuario = jrcUsuario;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public String getDescBreve() {
        return this.descBreve;
    }
    
    public void setDescBreve(String descBreve) {
        this.descBreve = descBreve;
    }
    public String getDescLonga() {
        return this.descLonga;
    }
    
    public void setDescLonga(String descLonga) {
        this.descLonga = descLonga;
    }
    public boolean isIndFracionada() {
        return this.indFracionada;
    }
    
    public void setIndFracionada(boolean indFracionada) {
        this.indFracionada = indFracionada;
    }
    public String getFlagTipo() {
        return this.flagTipo;
    }
    
    public void setFlagTipo(String flagTipo) {
        this.flagTipo = flagTipo;
    }
    public boolean isIndAtivo() {
        return this.indAtivo;
    }
    
    public void setIndAtivo(boolean indAtivo) {
        this.indAtivo = indAtivo;
    }
    public Date getDtInclusao() {
        return this.dtInclusao;
    }
    
    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }
    public Date getDtAlteracao() {
        return this.dtAlteracao;
    }
    
    public void setDtAlteracao(Date dtAlteracao) {
        this.dtAlteracao = dtAlteracao;
    }
    public long getVersaoSistema() {
        return this.versaoSistema;
    }
    
    public void setVersaoSistema(long versaoSistema) {
        this.versaoSistema = versaoSistema;
    }
    public long getVersaoRegistro() {
        return this.versaoRegistro;
    }
    
    public void setVersaoRegistro(long versaoRegistro) {
        this.versaoRegistro = versaoRegistro;
    }
    public String getHash1() {
        return this.hash1;
    }
    
    public void setHash1(String hash1) {
        this.hash1 = hash1;
    }
    public Set getJrcKits() {
        return this.jrcKits;
    }
    
    public void setJrcKits(Set jrcKits) {
        this.jrcKits = jrcKits;
    }
    public Set getJrcProdutos() {
        return this.jrcProdutos;
    }
    
    public void setJrcProdutos(Set jrcProdutos) {
        this.jrcProdutos = jrcProdutos;
    }
    public Set getJrcServicos() {
        return this.jrcServicos;
    }
    
    public void setJrcServicos(Set jrcServicos) {
        this.jrcServicos = jrcServicos;
    }
    public Set getJrcPedidoVendaItems() {
        return this.jrcPedidoVendaItems;
    }
    
    public void setJrcPedidoVendaItems(Set jrcPedidoVendaItems) {
        this.jrcPedidoVendaItems = jrcPedidoVendaItems;
    }




}


